const translations = {
    fr: {
        // Navigation
        "nav-home": "Accueil",
        "nav-disclaimer": "Avertissement Légal",
        "nav-privacy": "Confidentialité",

        // Hero Index
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Votre Lecteur Vidéo Ultime",
        "hero-subtitle": "Gérez et visionnez facilement vos propres listes de lecture (M3U, Xtream Codes) dans une interface de qualité premium, conçue pour Mobile et optimisée pour Android TV.",
        "hero-btn-download": "Télécharger l'App",
        "hero-btn-privacy": "Charte de Confidentialité",

        // Mockup
        "mockup-title": "Interface Cinématique Premium",
        "mockup-subtitle": "Une immersion visuelle totale avec gestion de l'historique et navigation fluide au D-Pad.",

        // Features Index
        "features-title": "Fonctionnalités Clés",
        "feat1-title": "Optimisé Android TV",
        "feat1-desc": "Une navigation D-pad Remote complète avec retours haptiques et animations fluides pour le confort de votre salon.",
        "feat2-title": "Lecteur ExoPlayer Rapide",
        "feat2-desc": "Décodage matériel ultra-rapide des flux HLS et TS. Zapping ultra-fluide et prise en charge des pistes audio/sous-titres intégrées.",
        "feat3-title": "Synchronisation Cloud",
        "feat3-desc": "Synchronisez de manière sécurisée vos favoris et votre historique \"Reprendre la lecture\" (Continue Watching) via Firebase entre vos appareils.",
        "feat4-title": "Zéro Contenu Inclus",
        "feat4-desc": "Une application technique 100 % neutre et légale. Nous ne fournissons aucun abonnement. Vous gardez le contrôle total de vos sources.",

        // Download Section
        "download-title": "Prêt à démarrer ?",
        "download-subtitle": "Installez IPTV Mediacenter sur votre téléphone, tablette, Android TV ou Windows et importez votre premier flux de test ou votre playlist personnelle.",
        "download-windows": "Télécharger pour Windows",
        "download-android": "Google Play Store (Bientôt)",
        "download-support": "Contacter le Support",

        // Footer
        "footer-desc": "Ce site web sert de portail de support technique et de conformité légale requis pour le déploiement sur les plateformes de téléchargement.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Tous droits réservés.",

        // Privacy Page
        "privacy-title": "Politique de Confidentialité",
        "privacy-date": "Dernière mise à jour : 26 mai 2026",
        "privacy-p1": "IPTV Mediacenter (\"nous\", \"notre\" ou \"l'Application\") s'engage à protéger votre vie privée. Cette politique de confidentialité explique comment nous traitons vos informations lorsque vous utilisez notre application mobile et Android TV.",
        "privacy-h1": "1. Aucun contenu fourni",
        "privacy-p2": "IPTV Mediacenter est un lecteur multimédia technique. Nous ne fournissons, n'hébergeons ni ne diffusons aucun contenu multimédia ou flux de télévision. Les utilisateurs doivent fournir leurs propres sources de contenu (par exemple, des listes de lecture M3U ou des identifiants Xtream Codes fournis légalement). Nous n'avons aucune affiliation avec des fournisseurs de contenu tiers.",
        "privacy-h2": "2. Collecte de données et respect de la vie privée",
        "privacy-p3": "Nous nous efforçons de collecter le moins de données possible afin de garantir votre confidentialité :",
        "privacy-li1": "<strong>Stockage local</strong> : Toutes les informations de connexion (URL du serveur, nom d'utilisateur, mot de passe) et les listes de chaînes sont stockées <strong>localement</strong> sur votre appareil via une base de données sécurisée.",
        "privacy-li2": "<strong>Authentification et synchronisation cloud</strong> : L'application utilise les services Firebase Authentication et Cloud Firestore (fournis par Google) pour vous permettre de créer un compte et de synchroniser vos <strong>Favoris et votre Historique de Lecture</strong> entre vos différents appareils.",
        "privacy-li3": "<strong>Identifiants de l'appareil</strong> : L'application peut collecter des identifiants techniques génériques (modèle d'appareil, version du système d'exploitation) afin de garantir la stabilité des flux et de respecter les limites de connexions simultanées de votre fournisseur d'accès.",
        "privacy-li4": "<strong>Pas de suivi publicitaire</strong> : Nous n'utilisons aucun tracker publicitaire tiers pour analyser votre comportement au sein de l'application.",
        "privacy-li5": "<strong>Sécurité des transferts</strong> : Toutes les données synchronisées avec le cloud sont cryptées et transférées de manière sécurisée via le protocole HTTPS.",
        "privacy-h3": "3. Utilisation des informations",
        "privacy-p4": "Les informations stockées localement sur votre appareil ou synchronisées sur votre compte cloud sécurisé sont utilisées exclusivement pour :",
        "privacy-li6": "Vous connecter à vos serveurs IPTV personnels.",
        "privacy-li7": "Afficher votre liste de chaînes et votre guide des programmes (EPG).",
        "privacy-li8": "Synchroniser vos favoris et reprendre la lecture de vos vidéos d'un appareil à un autre.",
        "privacy-h4": "4. Services tiers",
        "privacy-p5": "Lorsque vous ajoutez une URL de playlist ou des identifiants, votre appareil se connecte directement aux serveurs tiers de votre fournisseur IPTV. Ces serveurs externes sont régis par leurs propres politiques de confidentialité. Nous ne sommes pas responsables du traitement de vos données par ces tiers.",
        "privacy-h5": "5. Sécurité",
        "privacy-p6": "Nous utilisons les méthodes de chiffrement standards fournies par le système d'exploitation Android afin de protéger vos données de connexion stockées sur votre appareil.",
        "privacy-h6": "6. Vie privée des enfants",
        "privacy-p7": "Notre application ne collecte sciemment aucune donnée personnelle auprès d'enfants.",
        "privacy-h7": "7. Contact",
        "privacy-p8": "Si vous avez des questions concernant cette Politique de Confidentialité, vous pouvez nous contacter par e-mail à :",

        // Disclaimer Page
        "disc-title": "Avertissement Légal et Non-Responsabilité",
        "disc-date": "Date d'effet : 26 mai 2026",
        "disc-p1": "Ce logiciel est uniquement un outil de lecture multimédia et ne fournit, ne distribue, ni ne contient aucun contenu média de quelque nature que ce soit. Les utilisateurs doivent obligatoirement fournir leurs propres sources (listes de lecture M3U, identifiants de serveurs Xtream Codes, etc.).",
        "disc-h1": "1. Absence de contenu multimédia",
        "disc-p2": "IPTV Mediacenter ne fournit aucun flux vidéo, aucune chaîne de télévision, aucune bibliothèque de films ou de séries. L'application est un outil neutre qui décode et affiche les listes de lecture saisies volontairement par l'utilisateur.",
        "disc-h2": "2. Absence d'affiliation légale",
        "disc-p3": "IPTV Mediacenter n'a aucune affiliation, aucun partenariat, ni aucun lien commercial avec des fournisseurs de flux, des revendeurs d'abonnements ou des distributeurs de contenu IPTV. Nous ne vendons aucun abonnement ou accès multimédia.",
        "disc-h3": "3. Droits d'auteur et Piratage",
        "disc-p4": "Nous ne soutenons ni ne tolérons la diffusion ou la lecture de matériels protégés par le droit d'auteur sans l'autorisation explicite du titulaire de ces droits. Il est de la responsabilité stricte de l'utilisateur de s'assurer que ses sources de lecture IPTV sont conformes aux réglementations locales et internationales en vigueur. IPTV Mediacenter ne pourra être tenu responsable de l'utilisation frauduleuse du logiciel à des fins de lecture de contenus piratés.",
        "disc-h4": "4. Utilisation Conforme",
        "disc-p5": "L'utilisation de notre application doit se faire en stricte conformité avec les lois de votre pays de résidence. Tout usage illicite du logiciel relève de la responsabilité exclusive de l'utilisateur final.",
        "disc-h5": "5. Marques de tiers",
        "disc-p6": "Tous les logos, noms de produits ou marques mentionnés dans la documentation ou sur la fiche de présentation appartiennent à leurs propriétaires respectifs et ne constituent en aucun cas une approbation ou un partenariat de leur part.",

        // FAQ Section
        "faq-title": "Foire aux Questions (FAQ)",
        "faq-q1": "Qu'est-ce que IPTV Mediacenter ?",
        "faq-a1": "IPTV Mediacenter est un lecteur multimédia technique neutre et gratuit. Il vous permet de visionner vos propres listes de lecture (M3U, Xtream Codes) avec une interface utilisateur optimisée pour la télévision et le mobile.",
        "faq-q2": "L'application fournit-elle des chaînes ou des abonnements ?",
        "faq-a2": "Non. IPTV Mediacenter ne fournit aucun flux vidéo, aucune chaîne de télévision et aucun abonnement. Vous devez configurer et importer vos propres sources de diffusion légales.",
        "faq-q3": "Sur quels appareils puis-je installer l'application ?",
        "faq-a3": "L'application est optimisée pour Android TV (avec une navigation complète à la télécommande), les smartphones/tablettes Android, ainsi que pour Windows (téléchargeable sur le Microsoft Store)."
    },
    en: {
        "nav-home": "Home",
        "nav-disclaimer": "Legal Disclaimer",
        "nav-privacy": "Privacy Policy",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Your Ultimate Video Player",
        "hero-subtitle": "Manage and watch your own playlists (M3U, Xtream Codes) easily in a premium interface, designed for Mobile and optimized for Android TV.",
        "hero-btn-download": "Download App",
        "hero-btn-privacy": "Privacy Policy",
        "mockup-title": "Premium Cinematic Interface",
        "mockup-subtitle": "Full visual immersion with viewing history and smooth D-Pad navigation.",
        "features-title": "Key Features",
        "feat1-title": "Android TV Optimized",
        "feat1-desc": "Full D-pad Remote navigation with haptic feedback and smooth animations for your living room comfort.",
        "feat2-title": "Fast ExoPlayer Engine",
        "feat2-desc": "Ultra-fast hardware decoding for HLS and TS streams. Seamless zapping and support for embedded audio/subtitle tracks.",
        "feat3-title": "Cloud Sync",
        "feat3-desc": "Securely synchronize your favorites and \"Continue Watching\" history via Firebase cloud infrastructure.",
        "feat4-title": "Zero Content Included",
        "feat4-desc": "A 100% neutral and legal technical application. We do not provide subscriptions. You keep full control of your sources.",
        "download-title": "Ready to Start?",
        "download-subtitle": "Install IPTV Mediacenter on your phone, tablet, Android TV, or Windows and import your first test stream or personal playlist.",
        "download-windows": "Download for Windows",
        "download-android": "Google Play Store (Coming Soon)",
        "download-support": "Contact Support",
        "footer-desc": "This website serves as a technical support and legal compliance portal required for deployment on app stores.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. All rights reserved.",

        "privacy-title": "Privacy Policy",
        "privacy-date": "Last updated: May 26, 2026",
        "privacy-p1": "IPTV Mediacenter (\"us\", \"our\", or \"the Application\") is committed to protecting your privacy. This privacy policy explains how we handle your information when you use our mobile and Android TV application.",
        "privacy-h1": "1. No Content Provided",
        "privacy-p2": "IPTV Mediacenter is a technical media player. We do not provide, host, or stream any multimedia content or TV streams. Users must provide their own content sources (e.g. legally obtained M3U playlists or Xtream Codes credentials). We have no affiliation with any third-party content providers.",
        "privacy-h2": "2. Data Collection and Privacy Respect",
        "privacy-p3": "We strive to collect as little data as possible to guarantee your privacy:",
        "privacy-li1": "<strong>Local storage</strong>: All login information (server URL, username, password) and channel lists are stored <strong>locally</strong> on your device in a secure database.",
        "privacy-li2": "<strong>Authentication and cloud sync</strong>: The app uses Firebase Authentication and Cloud Firestore (provided by Google) to let you create an account and synchronize your <strong>Favorites and Playback History</strong> across your devices.",
        "privacy-li3": "<strong>Device identifiers</strong>: The app may collect generic technical identifiers (device model, OS version) to ensure stream stability and respect the simultaneous connection limits of your provider.",
        "privacy-li4": "<strong>No ad tracking</strong>: We do not use any third-party advertising trackers to analyze your behavior inside the app.",
        "privacy-li5": "<strong>Secure transfers</strong>: All data synchronized with the cloud is encrypted and securely transferred via HTTPS.",
        "privacy-h3": "3. Use of Information",
        "privacy-p4": "The information stored locally on your device or synchronized to your secure cloud account is used exclusively to:",
        "privacy-li6": "Connect to your personal IPTV servers.",
        "privacy-li7": "Display your channel list and electronic program guide (EPG).",
        "privacy-li8": "Synchronize your favorites and resume video playback from one device to another.",
        "privacy-h4": "4. Third-Party Services",
        "privacy-p5": "When you add a playlist URL or credentials, your device connects directly to your IPTV provider's third-party servers. These external servers are governed by their own privacy policies. We are not responsible for how your data is handled by these third parties.",
        "privacy-h5": "5. Security",
        "privacy-p6": "We use standard encryption methods provided by the Android OS to protect your connection data stored on your device.",
        "privacy-h6": "6. Children's Privacy",
        "privacy-p7": "Our application does not knowingly collect personal data from children.",
        "privacy-h7": "7. Contact",
        "privacy-p8": "If you have any questions regarding this Privacy Policy, you can contact us by email at:",

        "disc-title": "Legal Disclaimer and Non-Responsibility",
        "disc-date": "Effective Date: May 26, 2026",
        "disc-p1": "This software is strictly a media playback tool and does not provide, distribute, or contain any media content of any kind. Users must provide their own sources (M3U playlists, Xtream Codes server credentials, etc.).",
        "disc-h1": "1. Absence of Multimedia Content",
        "disc-p2": "IPTV Mediacenter does not provide any video streams, TV channels, or libraries of movies and series. The application is a neutral tool that decodes and displays the playlists voluntarily entered by the user.",
        "disc-h2": "2. Absence of Legal Affiliation",
        "disc-p3": "IPTV Mediacenter has no affiliation, partnership, or commercial link with stream providers, subscription resellers, or IPTV content distributors. We do not sell subscriptions or media access.",
        "disc-h3": "3. Copyright and Piracy",
        "disc-p4": "We do not support or tolerate the broadcasting or playing of copyrighted material without the explicit permission of the copyright holder. It is the user's strict responsibility to ensure that their IPTV streaming sources comply with active local and international regulations. IPTV Mediacenter cannot be held responsible for the unauthorized use of the software to play pirated content.",
        "disc-h4": "4. Compliant Use",
        "disc-p5": "The use of our application must comply strictly with the laws of your country of residence. Any illicit use of the software is the sole responsibility of the end user.",
        "disc-h5": "5. Third-Party Trademarks",
        "disc-p6": "All logos, product names, or trademarks mentioned in the documentation or presentation belong to their respective owners and in no way constitute an endorsement or partnership on their part.",

        // FAQ Section
        "faq-title": "Frequently Asked Questions (FAQ)",
        "faq-q1": "What is IPTV Mediacenter?",
        "faq-a1": "IPTV Mediacenter is a free and neutral media player. It allows you to watch your own playlists (M3U, Xtream Codes) with a user interface optimized for TV and mobile.",
        "faq-q2": "Does the application provide channels or subscriptions?",
        "faq-a2": "No. IPTV Mediacenter does not provide any video streams, TV channels, or subscriptions. You must configure and import your own legal streaming sources.",
        "faq-q3": "On which devices can I install the application?",
        "faq-a3": "The application is optimized for Android TV (with full remote control navigation), Android smartphones/tablets, and Windows (downloadable from the Microsoft Store)."
    },
    de: {
        "nav-home": "Startseite",
        "nav-disclaimer": "Haftungsausschluss",
        "nav-privacy": "Datenschutz",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Ihr ultimativer Videoplayer",
        "hero-subtitle": "Verwalten und streamen Sie Ihre eigenen Wiedergabelisten (M3U, Xtream Codes) ganz einfach in einer Premium-Oberfläche, die für Mobilgeräte entwickelt und für Android TV optimiert ist.",
        "hero-btn-download": "App herunterladen",
        "hero-btn-privacy": "Datenschutzerklärung",
        "mockup-title": "Kino-Interface Premium",
        "mockup-subtitle": "Volles visuelles Eintauchen mit Verlauf und flüssiger Navigation über das D-Pad.",
        "features-title": "Hauptfunktionen",
        "feat1-title": "Android TV optimiert",
        "feat1-desc": "Vollständige D-Pad-Navigation mit haptischem Feedback und flüssigen Animationen für Ihr Wohnzimmer.",
        "feat2-title": "Schnelle ExoPlayer-Engine",
        "feat2-desc": "Ultraschnelle Hardware-Dekodierung für HLS- und TS-Streams. Zappen ohne Verzögerung und Unterstützung integrierter Audiospuren/Untertitel.",
        "feat3-title": "Cloud-Synchronisation",
        "feat3-desc": "Synchronisieren Sie Favoriten und Verlauf sicher über die Firebase-Cloud-Infrastruktur zwischen all Ihren Geräten.",
        "feat4-title": "Keine Inhalte enthalten",
        "feat4-desc": "Eine 100% neutrale und legale technische Anwendung. Wir bieten keine Abonnements. Sie behalten die volle Kontrolle über Ihre Quellen.",
        "download-title": "Bereit zum Starten?",
        "download-subtitle": "Installieren Sie IPTV Mediacenter auf Ihrem Handy, Tablet, Android TV oder Windows und importieren Sie Ihre Playlist.",
        "download-windows": "Für Windows herunterladen",
        "download-android": "Google Play Store (Demnächst)",
        "download-support": "Support kontaktieren",
        "footer-desc": "Diese Website dient als Portal für technischen Support und die Einhaltung gesetzlicher Vorschriften, die für die Bereitstellung in App Stores erforderlich sind.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Alle Rechte vorbehalten.",

        "privacy-title": "Datenschutzerklärung",
        "privacy-date": "Zuletzt aktualisiert: 26. Mai 2026",
        "privacy-p1": "IPTV Mediacenter (\"wir\", \"uns\" oder \"die Anwendung\") verpflichtet sich, Ihre Privatsphäre zu schützen. Diese Datenschutzerklärung erklärt, wie wir mit Ihren Informationen umgehen.",
        "privacy-h1": "1. Keine Inhalte bereitgestellt",
        "privacy-p2": "IPTV Mediacenter ist ein technischer Mediaplayer. Wir bieten keine Multimedia-Inhalte oder TV-Streams an und hosten diese nicht. Die Benutzer müssen ihre eigenen Inhalte bereitstellen.",
        "privacy-h2": "2. Datenerfassung und Datenschutz",
        "privacy-p3": "Wir erfassen so wenig Daten wie möglich, um Ihre Privatsphäre zu schützen:",
        "privacy-li1": "<strong>Lokaler Speicher</strong>: Alle Zugangsdaten und Kanallisten werden lokal auf Ihrem Gerät in einer sicheren Datenbank gespeichert.",
        "privacy-li2": "<strong>Cloud-Synchronisierung</strong>: Wir verwenden Firebase Authentication und Firestore (von Google), um Favoriten und Verlauf zu synchronisieren.",
        "privacy-li3": "<strong>Gerätekennungen</strong>: Wir erfassen anonyme technische Daten für die Stream-Stabilität.",
        "privacy-li4": "<strong>Keine Werbung</strong>: Keine Werbe-Tracker von Drittanbietern vorhanden.",
        "privacy-li5": "<strong>Sicherheit</strong>: Alle Datenübertragungen in die Cloud erfolgen verschlüsselt über HTTPS.",
        "privacy-h3": "3. Verwendung der Informationen",
        "privacy-p4": "Die Daten werden ausschließlich verwendet, um die Streams abzuspielen, Favoriten zu synchronisieren und Kanäle anzuzeigen.",
        "privacy-h4": "4. Dienste von Drittanbietern",
        "privacy-p5": "Ihre Verbindung läuft direkt zu den Servern Ihres IPTV-Anbieters. Diese haben eigene Datenschutzbestimmungen.",
        "privacy-h5": "5. Sicherheit",
        "privacy-p6": "Wir nutzen die Verschlüsselungsmethoden des Betriebssystems.",
        "privacy-h6": "6. Privatsphäre von Kindern",
        "privacy-p7": "Wir erfassen wissentlich keine Daten von Kindern.",
        "privacy-h7": "7. Kontakt",
        "privacy-p8": "Bei Fragen zur Datenschutzerklärung kontaktieren Sie uns unter:",

        "disc-title": "Haftungsausschluss",
        "disc-date": "In Kraft getreten: 26. Mai 2026",
        "disc-p1": "Diese Software ist ein reines Medienwiedergabe-Tool und enthält keinerlei eigene Medien. Benutzer müssen ihre eigenen Wiedergabelisten bereitstellen.",
        "disc-h1": "1. Keine Multimedia-Inhalte",
        "disc-p2": "IPTV Mediacenter bietet keine Kanäle, Filme oder Serien an. Die App ist ein neutrales Werkzeug.",
        "disc-h2": "2. Keine Zugehörigkeit",
        "disc-p3": "IPTV Mediacenter hat keine Partnerschaften mit IPTV-Dienstanbietern. Wir verkaufen keine Abonnements.",
        "disc-h3": "3. Urheberrecht und Piraterie",
        "disc-p4": "Wir unterstützen keine unbefugte Wiedergabe urheberrechtlich geschützter Inhalte. Der Benutzer ist voll verantwortlich für die Einhaltung der Gesetze.",
        "disc-h4": "4. Konforme Nutzung",
        "disc-p5": "Die Nutzung der App muss den Gesetzen Ihres Wohnsitzlandes entsprechen.",
        "disc-h5": "5. Marken Dritter",
        "disc-p6": "Alle erwähnten Marken gehören ihren jeweiligen Eigentümern."
    },
    es: {
        "nav-home": "Inicio",
        "nav-disclaimer": "Aviso Legal",
        "nav-privacy": "Privacidad",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Su Reproductor de Video Definitivo",
        "hero-subtitle": "Administre y reproduzca sus propias listas de reproducción (M3U, Xtream Codes) en una interfaz premium, diseñada para móviles y optimizada para Android TV.",
        "hero-btn-download": "Descargar la Aplicación",
        "hero-btn-privacy": "Política de Privacidad",
        "mockup-title": "Interfaz Cinemática Premium",
        "mockup-subtitle": "Inmersión visual total con historial de reproducción y navegación fluida con D-Pad.",
        "features-title": "Características Claves",
        "feat1-title": "Optimizado para Android TV",
        "feat1-desc": "Navegación fluida y completa con mando a distancia D-pad con vibración y animaciones para el salón.",
        "feat2-title": "Motor de Reproducción Rápido",
        "feat2-desc": "Decodificación de hardware ultra rápida para HLS y TS. Zapping fluido y pistas de audio/subtítulos.",
        "feat3-title": "Sincronización en la Nube",
        "feat3-desc": "Sincronice de forma segura sus favoritos e historial de reproducción con Firebase entre sus dispositivos.",
        "feat4-title": "Sin Contenido Incluido",
        "feat4-desc": "Una aplicación técnica 100% neutra y legal. No vendemos suscripciones. Usted tiene el control total de sus fuentes.",
        "download-title": "¿Listo para empezar?",
        "download-subtitle": "Instale IPTV Mediacenter en su teléfono, tableta, Android TV o Windows e importe su lista de reproducción.",
        "download-windows": "Descargar para Windows",
        "download-android": "Google Play Store (Próximamente)",
        "download-support": "Contactar al Soporte",
        "footer-desc": "Este sitio web sirve como portal de soporte técnico y cumplimiento de normativas para tiendas de aplicaciones.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Todos los derechos reservados.",

        "privacy-title": "Política de Privacidad",
        "privacy-date": "Última actualización: 26 de mayo de 2026",
        "privacy-p1": "IPTV Mediacenter (\"nosotros\", \"nuestro\" o \"la Aplicación\") se compromete a proteger su privacidad. Esta política explica cómo tratamos sus datos.",
        "privacy-h1": "1. Sin contenido proporcionado",
        "privacy-p2": "IPTV Mediacenter es un reproductor técnico. No proporcionamos ni alojamos canales o transmisiones. Los usuarios deben proveer su contenido.",
        "privacy-h2": "2. Recopilación de datos y privacidad",
        "privacy-p3": "Buscamos recopilar la menor cantidad de datos para respetar su privacidad:",
        "privacy-li1": "<strong>Almacenamiento local</strong>: Credenciales y listas guardadas en una base de datos local en su dispositivo.",
        "privacy-li2": "<strong>Sincronización</strong>: Firebase almacena opcionalmente sus favoritos e historial.",
        "privacy-li3": "<strong>ID del dispositivo</strong>: Usado técnicamente para mantener la estabilidad del streaming.",
        "privacy-li4": "<strong>Sin publicidad</strong>: No hay herramientas de seguimiento publicitario.",
        "privacy-li5": "<strong>Seguridad</strong>: Tránsito de datos encriptado vía HTTPS.",
        "privacy-h3": "3. Uso de la información",
        "privacy-p4": "Los datos sirven solo para reproducir el contenido, gestionar canales y sincronizar dispositivos.",
        "privacy-h4": "4. Terceros",
        "privacy-p5": "Su conexión se realiza directamente con los servidores de su proveedor IPTV, regulados por sus políticas de privacidad.",
        "privacy-h5": "5. Seguridad",
        "privacy-p6": "Uso de encriptación del sistema operativo.",
        "privacy-h6": "6. Menores",
        "privacy-p7": "No recopilamos datos de niños.",
        "privacy-h7": "7. Contacto",
        "privacy-p8": "Para dudas sobre la privacidad, escríbanos a:",

        "disc-title": "Aviso Legal",
        "disc-date": "Fecha de entrada en vigor: 26 de mayo de 2026",
        "disc-p1": "Este software es solo una herramienta de reproducción y no contiene ningún medio. Los usuarios deben suministrar sus fuentes.",
        "disc-h1": "1. Sin contenido multimedia",
        "disc-p2": "IPTV Mediacenter no provee canales ni películas. Es una herramienta neutral.",
        "disc-h2": "2. Sin afiliación",
        "disc-p3": "No tenemos relación con proveedores de servicios de IPTV. No vendemos planes.",
        "disc-h3": "3. Derechos de autor",
        "disc-p4": "No avalamos la reproducción de material protegido por derechos de autor sin permiso. El usuario es responsable legalmente de sus fuentes.",
        "disc-h4": "4. Uso lícito",
        "disc-p5": "El uso del software debe respetar las leyes de su país.",
        "disc-h5": "5. Marcas",
        "disc-p6": "Todas las marcas pertenecen a sus respectivos dueños."
    },
    it: {
        "nav-home": "Home",
        "nav-disclaimer": "Note Legali",
        "nav-privacy": "Privacy",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Il tuo Lettore Video Definitivo",
        "hero-subtitle": "Gestisci e riproduci facilmente le tue playlist (M3U, Xtream Codes) in un'interfaccia premium, progettata per dispositivi mobili e ottimizzata per Android TV.",
        "hero-btn-download": "Scarica l'App",
        "hero-btn-privacy": "Informativa sulla Privacy",
        "mockup-title": "Interfaccia Cinemashow Premium",
        "mockup-subtitle": "Immersione visiva completa con cronologia di riproduzione e navigazione fluida tramite D-Pad.",
        "features-title": "Caratteristiche Principali",
        "feat1-title": "Ottimizzato per Android TV",
        "feat1-desc": "Navigazione completa D-pad con feedback aptico e animazioni fluide per la tua TV.",
        "feat2-title": "Motore ExoPlayer Rapido",
        "feat2-desc": "Decodifica hardware ultra-rapida per flussi HLS e TS. Zapping fluido e gestione audio/sottotitoli.",
        "feat3-title": "Sincronizzazione Cloud",
        "feat3-desc": "Sincronizza in modo sicuro i tuoi preferiti e la cronologia con Firebase tra tutti i tuoi dispositivi.",
        "feat4-title": "Nessun Contenuto Incluso",
        "feat4-desc": "Applicazione tecnica neutra al 100%. Non forniamo abbonamenti. Mantieni il controllo totale delle tue fonti.",
        "download-title": "Pronto a iniziare?",
        "download-subtitle": "Installa IPTV Mediacenter su telefono, tablet, Android TV o Windows e importa la tua playlist.",
        "download-windows": "Scarica per Windows",
        "download-android": "Google Play Store (Prossimamente)",
        "download-support": "Contatta il Supporto",
        "footer-desc": "Questo sito Web funge da portale di supporto tecnico e conformità legale richiesto per le piattaforme di download.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Tutti i diritti riservati.",

        "privacy-title": "Informativa sulla Privacy",
        "privacy-date": "Ultimo aggiornamento: 26 maggio 2026",
        "privacy-p1": "IPTV Mediacenter (\"noi\", \"nostro\" o \"l'Applicazione\") si impegna a proteggere la tua privacy. Questa informativa spiega come trattiamo i tuoi dati.",
        "privacy-h1": "1. Nessun contenuto fornito",
        "privacy-p2": "L'applicazione è solo un lettore neutro. Non forniamo o ospitiamo flussi TV o film. L'utente deve caricare i propri contenuti.",
        "privacy-h2": "2. Raccolta dati",
        "privacy-p3": "Raccogliamo solo i dati strettamente necessari per rispettare la tua privacy:",
        "privacy-li1": "<strong>Archiviazione locale</strong>: Credenziali e playlist salvate in locale sul tuo dispositivo.",
        "privacy-li2": "<strong>Sincronizzazione cloud</strong>: Firebase gestisce la sincronizzazione di cronologia e preferiti.",
        "privacy-li3": "<strong>ID dispositivo</strong>: Utilizzato per scopi di stabilità dello streaming.",
        "privacy-li4": "<strong>Nessuna pubblicità</strong>: Non ci sono tracker pubblicitari di terze parti.",
        "privacy-li5": "<strong>Sicurezza</strong>: Trasferimenti cifrati tramite HTTPS.",
        "privacy-h3": "3. Uso delle informazioni",
        "privacy-p4": "I dati sono utilizzati solo per la riproduzione, la visualizzazione dei canali e la sincronizzazione.",
        "privacy-h4": "4. Servizi di terze parti",
        "privacy-p5": "Il dispositivo si connette direttamente ai server del tuo provider IPTV, regolati dalle loro politiche.",
        "privacy-h5": "5. Sicurezza",
        "privacy-p6": "Crittografia del sistema operativo attiva.",
        "privacy-h6": "6. Minori",
        "privacy-p7": "Non raccogliamo dati da bambini.",
        "privacy-h7": "7. Contatti",
        "privacy-p8": "Per domande sulla privacy, scrivici a:",

        "disc-title": "Note Legali",
        "disc-date": "Data di entrata in vigore: 26 maggio 2026",
        "disc-p1": "Questo software è solo uno strumento di riproduzione multimediale e non include alcun contenuto. Gli utenti devono fornire le proprie playlist.",
        "disc-h1": "1. Assenza di contenuti multimediali",
        "disc-p2": "L'app non offre canali o filmati. È uno strumento neutro.",
        "disc-h2": "2. Nessuna affiliazione",
        "disc-p3": "Non abbiamo legami con fornitori IPTV o distributori. Non vendiamo abbonamenti.",
        "disc-h3": "3. Diritto d'autore",
        "disc-p4": "Non supportiamo lo streaming di contenuti protetti da copyright senza autorizzazione. L'utente è responsabile delle proprie fonti.",
        "disc-h4": "4. Uso conforme",
        "disc-p5": "Rispettare le leggi del proprio paese durante l'uso dell'applicazione.",
        "disc-h5": "5. Marchi",
        "disc-p6": "Tutti i marchi appartengono ai rispettivi proprietari."
    },
    nl: {
        "nav-home": "Startpagina",
        "nav-disclaimer": "Disclaimer",
        "nav-privacy": "Privacybeleid",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Uw Ultieme Videospeler",
        "hero-subtitle": "Beheer en bekijk eenvoudig uw eigen afspeellijsten (M3U, Xtream Codes) in een premium interface, ontworpen voor mobiel en geoptimaliseerd voor Android TV.",
        "hero-btn-download": "App Downloaden",
        "hero-btn-privacy": "Privacybeleid",
        "mockup-title": "Premium Bioscoop Interface",
        "mockup-subtitle": "Volledige visuele immersie met geschiedenis en soepele navigatie via D-Pad.",
        "features-title": "Belangrijkste Kenmerken",
        "feat1-title": "Android TV Geoptimaliseerd",
        "feat1-desc": "Volledige afstandsbediening D-pad navigatie met voelbare trillingen en vloeiende animaties voor uw tv.",
        "feat2-title": "Snelle ExoPlayer Engine",
        "feat2-desc": "Ultrasnelle hardwaredecodering van HLS- en TS-stromen. Zappen zonder vertraging en ingebouwde audio/ondertitels.",
        "feat3-title": "Cloud Synchronisatie",
        "feat3-desc": "Synchroniseer uw favorieten en geschiedenis veilig via de Firebase-cloud tussen uw apparaten.",
        "feat4-title": "Geen Inhoud Inbegrepen",
        "feat4-desc": "Een 100% neutrale en legale technische toepassing. Wij verkopen geen abonnementen. U houdt controle over uw bronnen.",
        "download-title": "Klaar om te starten?",
        "download-subtitle": "Installeer IPTV Mediacenter op uw telefoon, tablet, Android TV of Windows en importeer uw afspeellijst.",
        "download-windows": "Download voor Windows",
        "download-android": "Google Play Store (Binnenkort)",
        "download-support": "Contact opnemen met Support",
        "footer-desc": "Deze website dient als technisch ondersteunings- en juridisch nalevingsportaal vereist voor app-stores.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Alle rechten voorbehouden.",

        "privacy-title": "Privacybeleid",
        "privacy-date": "Laatst bijgewerkt: 26 mei 2026",
        "privacy-p1": "IPTV Mediacenter (\"wij\", \"ons\" of \"de Applicatie\") streeft ernaar uw privacy te beschermen. Dit beleid legt uit hoe we uw gegevens verwerken.",
        "privacy-h1": "1. Geen inhoud geleverd",
        "privacy-p2": "IPTV Mediacenter is een neutrale speler. We leveren of hosten geen tv-zenders of media. Gebruikers moeten hun eigen afspeellijsten laden.",
        "privacy-h2": "2. Gegevensverzameling",
        "privacy-p3": "We verzamelen zo min mogelijk gegevens om uw privacy te waarborgen:",
        "privacy-li1": "<strong>Lokale opslag</strong>: Inloggegevens en kanalenlijst lokaal opgeslagen op uw apparaat.",
        "privacy-li2": "<strong>Synchronisatie</strong>: Firebase synchroniseert optioneel uw favorieten en geschiedenis.",
        "privacy-li3": "<strong>Apparaat-ID</strong>: Gebruikt om de stabiliteit van de videostream te waarborgen.",
        "privacy-li4": "<strong>Geen advertenties</strong>: We gebruiken geen ad-trackers.",
        "privacy-li5": "<strong>Beveiliging</strong>: Versleutelde gegevensoverdracht via HTTPS.",
        "privacy-h3": "3. Gebruik van informatie",
        "privacy-p4": "De gegevens worden alleen gebruikt om verbinding te maken, kanalen te tonen en uw voorkeuren te bewaren.",
        "privacy-h4": "4. Diensten van derden",
        "privacy-p5": "Uw apparaat maakt rechtstreeks verbinding met de servers van uw IPTV-aanbieder, die hun eigen beleid hebben.",
        "privacy-h5": "5. Beveiliging",
        "privacy-p6": "Standaard OS-versleuteling gebruikt.",
        "privacy-h6": "6. Privacy van kinderen",
        "privacy-p7": "We verzamelen geen gegevens van minderjarigen.",
        "privacy-h7": "7. Contact",
        "privacy-p8": "Bij vragen over privacy kunt u contact opnemen via:",

        "disc-title": "Disclaimer",
        "disc-date": "Ingangsdatum: 26 mei 2026",
        "disc-p1": "Deze software is uitsluitend een afspeeltool en bevat geen eigen media. Gebruikers moeten hun eigen afspeellijst aanleveren.",
        "disc-h1": "1. Geen media-inhoud",
        "disc-p2": "IPTV Mediacenter biedt geen kanalen of videobibliotheken. De app is een neutraal hulpmiddel.",
        "disc-h2": "2. Geen banden",
        "disc-p3": "We hebben geen relatie met IPTV-aanbieders en verkopen geen abonnementen.",
        "disc-h3": "3. Auteursrecht en piraterij",
        "disc-p4": "We keuren het streamen van auteursrechtelijk beschermd materiaal zonder toestemming af. De gebruiker is verantwoordelijk voor zijn bronnen.",
        "disc-h4": "4. Correct gebruik",
        "disc-p5": "Het gebruik van de app moet voldoen aan de wetgeving in uw land.",
        "disc-h5": "5. Handelsmerken",
        "disc-p6": "Alle merken behoren toe aan hun respectieve eigenaren."
    },
    ar: {
        "nav-home": "الرئيسية",
        "nav-disclaimer": "إخلاء المسؤولية",
        "nav-privacy": "الخصوصية",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>مشغل الفيديو المثالي لك",
        "hero-subtitle": "قم بإدارة وتشغيل قوائم التشغيل الخاصة بك (M3U ، Xtream Codes) بسهولة في واجهة مميزة، مصممة للهواتف ومتوافقة تماماً مع أجهزة Android TV.",
        "hero-btn-download": "تحميل التطبيق",
        "hero-btn-privacy": "سياسة الخصوصية",
        "mockup-title": "واجهة سينمائية ممتازة",
        "mockup-subtitle": "انغماس بصري كامل مع سجل للمشاهدة وتصفح سلس باستخدام جهاز التحكم.",
        "features-title": "الميزات الرئيسية",
        "feat1-title": "متوافق مع شاشات التلفاز",
        "feat1-desc": "تصفح كامل وسلس بجهاز التحكم عن بعد مع حركات وتأثيرات بصرية مصممة لراحتك.",
        "feat2-title": "مشغل ExoPlayer سريع",
        "feat2-desc": "فك ترميز سريع جداً لبث القنوات (HLS و TS) مع دعم التنقل السريع والترجمات ومسارات الصوت.",
        "feat3-title": "المزامنة السحابية",
        "feat3-desc": "قم بمزامنة قنواتك المفضلة وسجل المشاهدة بأمان عبر خوادم Firebase بين جميع أجهزتك.",
        "feat4-title": "لا يتضمن أي محتوى",
        "feat4-desc": "تطبيق تقني محايد وقانوني بنسبة 100%. نحن لا نقدم اشتراكات. أنت تحتفظ بالتحكم الكامل في مصادرك.",
        "download-title": "جاهز للبدء؟",
        "download-subtitle": "قم بتثبيت IPTV Mediacenter على هاتفك أو جهازك اللوحي أو شاشة التلفاز أو نظام Windows وابدأ بتشغيل قائمتك.",
        "download-windows": "تحميل لنظام Windows",
        "download-android": "متجر Google Play (قريباً)",
        "download-support": "الاتصال بالدعم",
        "footer-desc": "يعمل هذا الموقع كبوابة للدعم الفني والامتثال القانوني المطلوب للنشر في متاجر التطبيقات.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. جميع الحقوق محفوظة.",

        "privacy-title": "سياسة الخصوصية",
        "privacy-date": "آخر تحديث: 26 مايو 2026",
        "privacy-p1": "يلتزم IPTV Mediacenter (\"نحن\" أو \"تطبيقنا\") بحماية خصوصيتك. توضح سياسة الخصوصية هذه كيفية التعامل مع بياناتك عند الاستخدام.",
        "privacy-h1": "1. لا نقدم أي محتوى",
        "privacy-p2": "التطبيق هو مجرد مشغل وسائط محايد. نحن لا نقدم أو نستضيف أي قنوات تلفزيونية أو بث مباشر. يجب على المستخدم توفير المحتوى الخاص به.",
        "privacy-h2": "2. جمع البيانات والخصوصية",
        "privacy-p3": "نحن نحرص على جمع أقل قدر ممكن من البيانات للحفاظ على خصوصيتك:",
        "privacy-li1": "<strong>التخزين المحلي</strong>: يتم حفظ جميع بيانات تسجيل الدخول وقوائم القنوات محلياً على جهازك في قاعدة بيانات آمنة.",
        "privacy-li2": "<strong>المزامنة السحابية</strong>: نستخدم خدمات Firebase لمزامنة المفضلة وسجل المشاهدة اختيارياً.",
        "privacy-li3": "<strong>معرفات الجهاز</strong>: قد نجمع بيانات تقنية عامة للحفاظ على استقرار تشغيل البث المباشر.",
        "privacy-li4": "<strong>لا توجد إعلانات</strong>: لا نستخدم أي أدوات تتبع إعلانية لأطراف خارجية.",
        "privacy-li5": "<strong>الأمان</strong>: يتم نقل جميع البيانات المشتركة مع السحابة بشكل مشفر عبر بروتوكول HTTPS الآمن.",
        "privacy-h3": "3. استخدام المعلومات",
        "privacy-p4": "تستخدم البيانات فقط للاتصال بالخادم الخاص بك وعرض دليل البرامج (EPG) ومزامنة تفضيلاتك.",
        "privacy-h4": "4. خدمات الطرف الثالث",
        "privacy-p5": "يتصل جهازك مباشرة بخوادم موزع الخدمة الخاص بك، وتخضع هذه الاتصالات لسياسة الخصوصية الخاصة بهم.",
        "privacy-h5": "5. الحماية والأمان",
        "privacy-p6": "نستخدم تقنيات التشفير القياسية المضمنة في نظام التشغيل لحماية بياناتك.",
        "privacy-h6": "6. خصوصية الأطفال",
        "privacy-p7": "تطبيقنا لا يجمع أي بيانات من الأطفال عن علم.",
        "privacy-h7": "7. اتصل بنا",
        "privacy-p8": "إذا كان لديك أي أسئلة حول الخصوصية، يمكنك التواصل معنا عبر البريد الإلكتروني:",

        "disc-title": "إخلاء المسؤولية القانونية",
        "disc-date": "تاريخ النفاذ: 26 مايو 2026",
        "disc-p1": "هذا البرنامج هو مجرد أداة لتشغيل الوسائط ولا يحتوي أو يوزع أي محتوى وسائط على الإطلاق. يجب على المستخدمين تقديم مصادرهم الخاصة.",
        "disc-h1": "1. خلو التطبيق من القنوات والمحتوى",
        "disc-p2": "لا يوفر IPTV Mediacenter أي قنوات تلفزيونية أو مكتبات أفلام. التطبيق أداة تقنية محايدة فقط.",
        "disc-h2": "2. عدم التبعية لأي جهة",
        "disc-p3": "ليس لدينا أي شراكة أو علاقة تجارية مع أي موزع قنوات أو اشتراكات IPTV. نحن لا نبيع أي اشتراكات.",
        "disc-h3": "3. حقوق النشر وحقوق الملكية",
        "disc-p4": "نحن لا ندعم تشغيل المواد المحمية بحقوق النشر دون إذن صاحب الحق. تقع المسؤولية الكاملة على المستخدم للتأكد من قانونية مصادره.",
        "disc-h4": "4. الاستخدام القانوني",
        "disc-p5": "يجب أن يتوافق استخدام التطبيق مع القوانين واللوائح السارية في بلد إقامتك.",
        "disc-h5": "5. العلامات التجارية",
        "disc-p6": "جميع العلامات التجارية والشعارات المذكورة هي ملك لأصحابها ولا تعني أي شراكة معنا."
    }
};

function changeLanguage(lang) {
    localStorage.setItem("selected_lang", lang);
    applyTranslations(lang);
}

function applyTranslations(lang) {
    const dict = translations[lang] || translations["fr"];
    
    // Set html lang and dir attributes
    document.documentElement.lang = lang;
    if (lang === "ar") {
        document.documentElement.dir = "rtl";
        document.body.classList.add("rtl-layout");
    } else {
        document.documentElement.dir = "ltr";
        document.body.classList.remove("rtl-layout");
    }

    // Translate all elements with data-i18n
    document.querySelectorAll("[data-i18n]").forEach(element => {
        const key = element.getAttribute("data-i18n");
        if (dict[key]) {
            if (element.tagName === "INPUT" || element.tagName === "TEXTAREA") {
                element.placeholder = dict[key];
            } else {
                element.innerHTML = dict[key];
            }
        }
    });
    
    // Update language select dropdown value
    const langSelect = document.getElementById("lang-select");
    if (langSelect) {
        langSelect.value = lang;
    }
}

// Automatically detect language on load
document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("selected_lang");
    const browserLang = navigator.language.substring(0, 2);
    const defaultLang = savedLang || (translations[browserLang] ? browserLang : "fr");
    applyTranslations(defaultLang);
});
