const translations = {
    fr: {
        // Navigation
        "nav-home": "Accueil",
        "nav-disclaimer": "Avertissement Légal",
        "nav-privacy": "Confidentialité",

        // Hero Index
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Votre Lecteur Vidéo Ultime",
        "hero-subtitle": "Gérez et visionnez facilement vos propres listes de lecture (M3U, Xtream Codes) dans une interface de qualité premium, conçue pour Mobile et optimisée pour Android TV.",
        "hero-btn-download": "Télécharger l'App",
        "hero-btn-privacy": "Charte de Confidentialité",

        // Mockup
        "mockup-title": "Interface Cinématique Premium",
        "mockup-subtitle": "Une immersion visuelle totale avec gestion de l'historique et navigation fluide au D-Pad.",

        // Features Index
        "features-title": "Fonctionnalités Clés",
        "feat1-title": "Optimisé Android TV",
        "feat1-desc": "Une navigation D-pad Remote complète avec retours haptiques et animations fluides pour le confort de votre salon.",
        "feat2-title": "Lecteur ExoPlayer Rapide",
        "feat2-desc": "Décodage matériel ultra-rapide des flux HLS et TS. Zapping ultra-fluide et prise en charge des pistes audio/sous-titres intégrées.",
        "feat3-title": "Synchronisation Cloud",
        "feat3-desc": "Synchronisez de manière sécurisée vos favoris et votre historique \"Reprendre la lecture\" (Continue Watching) via Firebase entre vos appareils.",
        "feat4-title": "Zéro Contenu Inclus",
        "feat4-desc": "Une application technique 100 % neutre et légale. Nous ne fournissons aucun abonnement. Vous gardez le contrôle total de vos sources.",

        // Download Section
        "download-title": "Prêt à démarrer ?",
        "download-subtitle": "Installez IPTV Mediacenter sur votre téléphone, tablette, Android TV ou Windows et importez votre premier flux de test ou votre playlist personnelle.",
        "download-windows": "Télécharger pour Windows",
        "download-android": "Google Play Store",
        "download-support": "Contacter le Support",
        "download-discord": "Rejoindre le Discord",

        // Footer
        "footer-desc": "Ce site web sert de portail de support technique et de conformité légale requis pour le déploiement sur les plateformes de téléchargement.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Tous droits réservés.",

        // Privacy Page
        "privacy-title": "Politique de Confidentialité",
        "privacy-date": "Dernière mise à jour : 26 avril 2026",
        "privacy-p1": "IPTV Mediacenter (\"nous\", \"notre\" ou \"l'Application\") s'engage à protéger votre vie privée. Cette politique de confidentialité explique comment nous traitons vos informations lorsque vous utilisez notre application mobile et Android TV.",
        "privacy-h1": "1. Aucun contenu fourni",
        "privacy-p2": "IPTV Mediacenter est un lecteur multimédia technique. Nous ne fournissons, n'hébergeons ni ne diffusons aucun contenu multimédia ou flux de télévision. Les utilisateurs doivent fournir leurs propres sources de contenu (par exemple, des listes de lecture M3U ou des identifiants Xtream Codes fournis légalement). Nous n'avons aucune affiliation avec des fournisseurs de contenu tiers.",
        "privacy-h2": "2. Collecte de données et respect de la vie privée",
        "privacy-p3": "Nous nous efforçons de collecter le moins de données possible afin de garantir votre confidentialité :",
        "privacy-li1": "<strong>Stockage local</strong> : Toutes les informations de connexion (URL du serveur, nom d'utilisateur, mot de passe) et les listes de chaînes sont stockées <strong>localement</strong> sur votre appareil via une base de données sécurisée.",
        "privacy-li2": "<strong>Authentification et synchronisation cloud</strong> : L'application utilise les services Firebase Authentication et Cloud Firestore (fournis par Google) pour vous permettre de créer un compte et de synchroniser vos <strong>Favoris et votre Historique de Lecture</strong> entre vos différents appareils.",
        "privacy-li3": "<strong>Identifiants de l'appareil</strong> : L'application peut collecter des identifiants techniques génériques (modèle d'appareil, version du système d'exploitation) afin de garantir la stabilité des flux et de respecter les limites de connexions simultanées de votre fournisseur d'accès.",
        "privacy-li-sentry": "<strong>Rapports de crash et diagnostics</strong> : Nous utilisons <strong>Sentry</strong> (par Functional Software, Inc.) pour collecter des journaux de crash anonymes et des informations de diagnostic en cas d'erreur inattendue. Ces données (modèle d'appareil, version de l'OS, stack trace) sont utilisées uniquement pour améliorer la stabilité et ne contiennent aucune information personnellement identifiable.",
        "privacy-li4": "<strong>Pas de suivi publicitaire</strong> : Nous n'utilisons aucun tracker publicitaire tiers pour analyser votre comportement au sein de l'application.",
        "privacy-li5": "<strong>Sécurité des transferts</strong> : Toutes les données synchronisées avec le cloud sont cryptées et transférées de manière sécurisée via le protocole HTTPS.",
        "privacy-h3": "3. Utilisation des informations",
        "privacy-p4": "Les informations stockées localement sur votre appareil ou synchronisées sur votre compte cloud sécurisé sont utilisées exclusivement pour :",
        "privacy-li6": "Vous connecter à vos serveurs IPTV personnels.",
        "privacy-li7": "Afficher votre liste de chaînes et votre guide des programmes (EPG).",
        "privacy-li8": "Synchroniser vos favoris et reprendre la lecture de vos vidéos d'un appareil à un autre.",
        "privacy-h4": "4. Services tiers",
        "privacy-p5": "Nous utilisons <strong>Firebase (Google)</strong> pour l'authentification et la synchronisation cloud, ainsi que <strong>Sentry</strong> pour les rapports de crash. De plus, lorsque vous ajoutez une URL de playlist ou des identifiants, votre appareil se connecte directement aux serveurs tiers de votre fournisseur IPTV. Ces serveurs externes sont régis par leurs propres politiques de confidentialité. Nous ne sommes pas responsables du traitement de vos données par ces tiers.",
        "privacy-h5": "5. Sécurité",
        "privacy-p6": "Nous utilisons les méthodes de chiffrement standards fournies par le système d'exploitation Android afin de protéger vos données de connexion stockées sur votre appareil.",
        "privacy-h6": "6. Vie privée des enfants",
        "privacy-p7": "Notre application ne collecte sciemment aucune donnée personnelle auprès d'enfants.",
        "privacy-h7": "7. Contact",
        "privacy-p8": "Si vous avez des questions concernant cette Politique de Confidentialité, vous pouvez nous contacter par e-mail à :",

        // Disclaimer Page
        "disc-title": "Avertissement Légal et Non-Responsabilité",
        "disc-date": "Date d'effet : 26 mai 2026",
        "disc-p1": "Ce logiciel est uniquement un outil de lecture multimédia et ne fournit, ne distribue, ni ne contient aucun contenu média de quelque nature que ce soit. Les utilisateurs doivent obligatoirement fournir leurs propres sources (listes de lecture M3U, identifiants de serveurs Xtream Codes, etc.).",
        "disc-h1": "1. Absence de contenu multimédia",
        "disc-p2": "IPTV Mediacenter ne fournit aucun flux vidéo, aucune chaîne de télévision, aucune bibliothèque de films ou de séries. L'application est un outil neutre qui décode et affiche les listes de lecture saisies volontairement par l'utilisateur.",
        "disc-h2": "2. Absence d'affiliation légale",
        "disc-p3": "IPTV Mediacenter n'a aucune affiliation, aucun partenariat, ni aucun lien commercial avec des fournisseurs de flux, des revendeurs d'abonnements ou des distributeurs de contenu IPTV. Nous ne vendons aucun abonnement ou accès multimédia.",
        "disc-h3": "3. Droits d'auteur et Piratage",
        "disc-p4": "Nous ne soutenons ni ne tolérons la diffusion ou la lecture de matériels protégés par le droit d'auteur sans l'autorisation explicite du titulaire de ces droits. Il est de la responsabilité stricte de l'utilisateur de s'assurer que ses sources de lecture IPTV sont conformes aux réglementations locales et internationales en vigueur. IPTV Mediacenter ne pourra être tenu responsable de l'utilisation frauduleuse du logiciel à des fins de lecture de contenus piratés.",
        "disc-h4": "4. Utilisation Conforme",
        "disc-p5": "L'utilisation de notre application doit se faire en stricte conformité avec les lois de votre pays de résidence. Tout usage illicite du logiciel relève de la responsabilité exclusive de l'utilisateur final.",
        "disc-h5": "5. Marques de tiers",
        "disc-p6": "Tous les logos, noms de produits ou marques mentionnés dans la documentation ou sur la fiche de présentation appartiennent à leurs propriétaires respectifs et ne constituent en aucun cas une approbation ou un partenariat de leur part.",

        // FAQ Section
        "faq-title": "Foire aux Questions (FAQ)",
        "faq-q1": "Qu'est-ce que IPTV Mediacenter ?",
        "faq-a1": "IPTV Mediacenter est un lecteur multimédia technique neutre et gratuit. Il vous permet de visionner vos propres listes de lecture (M3U, Xtream Codes) avec une interface utilisateur optimisée pour la télévision et le mobile.",
        "faq-q2": "L'application fournit-elle des chaînes ou des abonnements ?",
        "faq-a2": "Non. IPTV Mediacenter ne fournit aucun flux vidéo, aucune chaîne de télévision et aucun abonnement. Vous devez configurer et importer vos propres sources de diffusion légales.",
        "faq-q3": "Sur quels appareils puis-je installer l'application ?",
        "faq-a3": "L'application est optimisée pour Android TV (avec une navigation complète à la télécommande), les smartphones/tablettes Android, ainsi que pour Windows (téléchargeable sur le Microsoft Store)."
    },
    en: {
        "nav-home": "Home",
        "nav-disclaimer": "Legal Disclaimer",
        "nav-privacy": "Privacy Policy",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Your Ultimate Video Player",
        "hero-subtitle": "Manage and watch your own playlists (M3U, Xtream Codes) easily in a premium interface, designed for Mobile and optimized for Android TV.",
        "hero-btn-download": "Download App",
        "hero-btn-privacy": "Privacy Policy",
        "mockup-title": "Premium Cinematic Interface",
        "mockup-subtitle": "Full visual immersion with viewing history and smooth D-Pad navigation.",
        "features-title": "Key Features",
        "feat1-title": "Android TV Optimized",
        "feat1-desc": "Full D-pad Remote navigation with haptic feedback and smooth animations for your living room comfort.",
        "feat2-title": "Fast ExoPlayer Engine",
        "feat2-desc": "Ultra-fast hardware decoding for HLS and TS streams. Seamless zapping and support for embedded audio/subtitle tracks.",
        "feat3-title": "Cloud Sync",
        "feat3-desc": "Securely synchronize your favorites and \"Continue Watching\" history via Firebase cloud infrastructure.",
        "feat4-title": "Zero Content Included",
        "feat4-desc": "A 100% neutral and legal technical application. We do not provide subscriptions. You keep full control of your sources.",
        "download-title": "Ready to Start?",
        "download-subtitle": "Install IPTV Mediacenter on your phone, tablet, Android TV, or Windows and import your first test stream or personal playlist.",
        "download-windows": "Download for Windows",
        "download-android": "Google Play Store",
        "download-support": "Contact Support",
        "download-discord": "Join our Discord",
        "footer-desc": "This website serves as a technical support and legal compliance portal required for deployment on app stores.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. All rights reserved.",

        "privacy-title": "Privacy Policy",
        "privacy-date": "Last updated: April 26, 2026",
        "privacy-p1": "IPTV Mediacenter (\"us\", \"our\", or \"the Application\") is committed to protecting your privacy. This privacy policy explains how we handle your information when you use our mobile and Android TV application.",
        "privacy-h1": "1. No Content Provided",
        "privacy-p2": "IPTV Mediacenter is a technical media player. We do not provide, host, or stream any multimedia content or TV streams. Users must provide their own content sources (e.g. legally obtained M3U playlists or Xtream Codes credentials). We have no affiliation with any third-party content providers.",
        "privacy-h2": "2. Data Collection and Privacy Respect",
        "privacy-p3": "We strive to collect as little data as possible to guarantee your privacy:",
        "privacy-li1": "<strong>Local storage</strong>: All login information (server URL, username, password) and channel lists are stored <strong>locally</strong> on your device in a secure database.",
        "privacy-li2": "<strong>Authentication and cloud sync</strong>: The app uses Firebase Authentication and Cloud Firestore (provided by Google) to let you create an account and synchronize your <strong>Favorites and Playback History</strong> across your devices.",
        "privacy-li3": "<strong>Device identifiers</strong>: The app may collect generic technical identifiers (device model, OS version) to ensure stream stability and respect the simultaneous connection limits of your provider.",
        "privacy-li-sentry": "<strong>Crash Reporting & Diagnostics</strong>: We use <strong>Sentry</strong> (by Functional Software, Inc.) to collect anonymous crash logs and diagnostic information when the App encounters an unexpected error. This includes technical details such as device model, OS version, application version, and the stack trace of the error. We use this data solely to improve the stability and performance of the App. No personally identifiable information is sent to Sentry.",
        "privacy-li4": "<strong>No ad tracking</strong>: We do not use any third-party advertising trackers to analyze your behavior inside the app.",
        "privacy-li5": "<strong>Secure transfers</strong>: All data synchronized with the cloud is encrypted and securely transferred via HTTPS.",
        "privacy-h3": "3. Use of Information",
        "privacy-p4": "The information stored locally on your device or synchronized to your secure cloud account is used exclusively to:",
        "privacy-li6": "Connect to your personal IPTV servers.",
        "privacy-li7": "Display your channel list and electronic program guide (EPG).",
        "privacy-li8": "Synchronize your favorites and resume video playback from one device to another.",
        "privacy-h4": "4. Third-Party Services",
        "privacy-p5": "We use <strong>Firebase (Google)</strong> for cloud authentication and synchronization, and <strong>Sentry</strong> for crash reporting. Additionally, when you add a playlist URL or credentials, your device connects directly to your IPTV provider's third-party servers. These external servers are governed by their own privacy policies. We are not responsible for how your data is handled by these third parties.",
        "privacy-h5": "5. Security",
        "privacy-p6": "We use standard encryption methods provided by the Android OS to protect your connection data stored on your device.",
        "privacy-h6": "6. Children's Privacy",
        "privacy-p7": "Our application does not knowingly collect personal data from children.",
        "privacy-h7": "7. Contact",
        "privacy-p8": "If you have any questions regarding this Privacy Policy, you can contact us by email at:",

        "disc-title": "Legal Disclaimer and Non-Responsibility",
        "disc-date": "Effective Date: May 26, 2026",
        "disc-p1": "This software is strictly a media playback tool and does not provide, distribute, or contain any media content of any kind. Users must provide their own sources (M3U playlists, Xtream Codes server credentials, etc.).",
        "disc-h1": "1. Absence of Multimedia Content",
        "disc-p2": "IPTV Mediacenter does not provide any video streams, TV channels, or libraries of movies and series. The application is a neutral tool that decodes and displays the playlists voluntarily entered by the user.",
        "disc-h2": "2. Absence of Legal Affiliation",
        "disc-p3": "IPTV Mediacenter has no affiliation, partnership, or commercial link with stream providers, subscription resellers, or IPTV content distributors. We do not sell subscriptions or media access.",
        "disc-h3": "3. Copyright and Piracy",
        "disc-p4": "We do not support or tolerate the broadcasting or playing of copyrighted material without the explicit permission of the copyright holder. It is the user's strict responsibility to ensure that their IPTV streaming sources comply with active local and international regulations. IPTV Mediacenter cannot be held responsible for the unauthorized use of the software to play pirated content.",
        "disc-h4": "4. Compliant Use",
        "disc-p5": "The use of our application must comply strictly with the laws of your country of residence. Any illicit use of the software is the sole responsibility of the end user.",
        "disc-h5": "5. Third-Party Trademarks",
        "disc-p6": "All logos, product names, or trademarks mentioned in the documentation or presentation belong to their respective owners and in no way constitute an endorsement or partnership on their part.",

        // FAQ Section
        "faq-title": "Frequently Asked Questions (FAQ)",
        "faq-q1": "What is IPTV Mediacenter?",
        "faq-a1": "IPTV Mediacenter is a free and neutral media player. It allows you to watch your own playlists (M3U, Xtream Codes) with a user interface optimized for TV and mobile.",
        "faq-q2": "Does the application provide channels or subscriptions?",
        "faq-a2": "No. IPTV Mediacenter does not provide any video streams, TV channels, or subscriptions. You must configure and import your own legal streaming sources.",
        "faq-q3": "On which devices can I install the application?",
        "faq-a3": "The application is optimized for Android TV (with full remote control navigation), Android smartphones/tablets, and Windows (downloadable from the Microsoft Store)."
    },
    de: {
        "nav-home": "Startseite",
        "nav-disclaimer": "Haftungsausschluss",
        "nav-privacy": "Datenschutz",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Ihr ultimativer Videoplayer",
        "hero-subtitle": "Verwalten und streamen Sie Ihre eigenen Wiedergabelisten (M3U, Xtream Codes) ganz einfach in einer Premium-Oberfläche, die für Mobilgeräte entwickelt und für Android TV optimiert ist.",
        "hero-btn-download": "App herunterladen",
        "hero-btn-privacy": "Datenschutzerklärung",
        "mockup-title": "Kino-Interface Premium",
        "mockup-subtitle": "Volles visuelles Eintauchen mit Verlauf und flüssiger Navigation über das D-Pad.",
        "features-title": "Hauptfunktionen",
        "feat1-title": "Android TV optimiert",
        "feat1-desc": "Vollständige D-Pad-Navigation mit haptischem Feedback und flüssigen Animationen für Ihr Wohnzimmer.",
        "feat2-title": "Schnelle ExoPlayer-Engine",
        "feat2-desc": "Ultraschnelle Hardware-Dekodierung für HLS- und TS-Streams. Zappen ohne Verzögerung und Unterstützung integrierter Audiospuren/Untertitel.",
        "feat3-title": "Cloud-Synchronisation",
        "feat3-desc": "Synchronisieren Sie Favoriten und Verlauf sicher über die Firebase-Cloud-Infrastruktur zwischen all Ihren Geräten.",
        "feat4-title": "Keine Inhalte enthalten",
        "feat4-desc": "Eine 100% neutrale und legale technische Anwendung. Wir bieten keine Abonnements. Sie behalten die volle Kontrolle über Ihre Quellen.",
        "download-title": "Bereit zum Starten?",
        "download-subtitle": "Installieren Sie IPTV Mediacenter auf Ihrem Handy, Tablet, Android TV oder Windows und importieren Sie Ihre Playlist.",
        "download-windows": "Für Windows herunterladen",
        "download-android": "Google Play Store",
        "download-support": "Support kontaktieren",
        "download-discord": "Discord beitreten",
        "footer-desc": "Diese Website dient als Portal für technischen Support und die Einhaltung gesetzlicher Vorschriften, die für die Bereitstellung in App Stores erforderlich sind.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Alle Rechte vorbehalten.",

        "privacy-title": "Datenschutzerklärung",
        "privacy-date": "Zuletzt aktualisiert: 26. April 2026",
        "privacy-p1": "IPTV Mediacenter (\"wir\", \"uns\" oder \"die Anwendung\") verpflichtet sich, Ihre Privatsphäre zu schützen. Diese Datenschutzerklärung erklärt, wie wir mit Ihren Informationen umgehen.",
        "privacy-h1": "1. Keine Inhalte bereitgestellt",
        "privacy-p2": "IPTV Mediacenter ist ein technischer Mediaplayer. Wir bieten keine Multimedia-Inhalte oder TV-Streams an und hosten diese nicht. Die Benutzer müssen ihre eigenen Inhalte bereitstellen.",
        "privacy-h2": "2. Datenerfassung und Datenschutz",
        "privacy-p3": "Wir erfassen so wenig Daten wie möglich, um Ihre Privatsphäre zu schützen:",
        "privacy-li1": "<strong>Lokaler Speicher</strong>: Alle Zugangsdaten und Kanallisten werden lokal auf Ihrem Gerät in einer sicheren Datenbank gespeichert.",
        "privacy-li2": "<strong>Cloud-Synchronisierung</strong>: Wir verwenden Firebase Authentication und Firestore (von Google), um Favoriten und Verlauf zu synchronisieren.",
        "privacy-li3": "<strong>Gerätekennungen</strong>: Wir erfassen anonyme technische Daten für die Stream-Stabilität.",
        "privacy-li-sentry": "<strong>Absturzberichte & Diagnose</strong>: Wir verwenden <strong>Sentry</strong> (von Functional Software, Inc.), um anonyme Absturzprotokolle und Diagnoseinformationen zu sammeln, wenn die App auf einen unerwarteten Fehler stößt. Dies umfasst technische Details wie Gerätemodell, Betriebssystemversion, Anwendungsversion und den Stacktrace des Fehlers. Diese Daten dienen ausschließlich der Verbesserung der Stabilität und Leistung. Es werden keine personenbezogenen Daten an Sentry gesendet.",
        "privacy-li4": "<strong>Keine Werbung</strong>: Keine Werbe-Tracker von Drittanbietern vorhanden.",
        "privacy-li5": "<strong>Sicherheit</strong>: Alle Datenübertragungen in die Cloud erfolgen verschlüsselt über HTTPS.",
        "privacy-h3": "3. Verwendung der Informationen",
        "privacy-p4": "Die Daten werden ausschließlich verwendet, um die Streams abzuspielen, Favoriten zu synchronisieren und Kanäle anzuzeigen.",
        "privacy-h4": "4. Dienste von Drittanbietern",
        "privacy-p5": "Wir nutzen <strong>Firebase (Google)</strong> für die Cloud-Authentifizierung und Synchronisierung sowie <strong>Sentry</strong> für Absturzberichte. Darüber hinaus läuft Ihre Verbindung direkt zu den Servern Ihres IPTV-Anbieters, welche eigene Datenschutzbestimmungen haben.",
        "privacy-h5": "5. Sicherheit",
        "privacy-p6": "Wir nutzen die Verschlüsselungsmethoden des Betriebssystems.",
        "privacy-h6": "6. Privatsphäre von Kindern",
        "privacy-p7": "Wir erfassen wissentlich keine Daten von Kindern.",
        "privacy-h7": "7. Kontakt",
        "privacy-p8": "Bei Fragen zur Datenschutzerklärung kontaktieren Sie uns unter:",

        "disc-title": "Haftungsausschluss",
        "disc-date": "In Kraft getreten: 26. Mai 2026",
        "disc-p1": "Diese Software ist ein reines Medienwiedergabe-Tool und enthält keinerlei eigene Medien. Benutzer müssen ihre eigenen Wiedergabelisten bereitstellen.",
        "disc-h1": "1. Keine Multimedia-Inhalte",
        "disc-p2": "IPTV Mediacenter bietet keine Kanäle, Filme oder Serien an. Die App ist ein neutrales Werkzeug.",
        "disc-h2": "2. Keine Zugehörigkeit",
        "disc-p3": "IPTV Mediacenter hat keine Partnerschaften mit IPTV-Dienstanbietern. Wir verkaufen keine Abonnements.",
        "disc-h3": "3. Urheberrecht und Piraterie",
        "disc-p4": "Wir unterstützen keine unbefugte Wiedergabe urheberrechtlich geschützter Inhalte. Der Benutzer ist voll verantwortlich für die Einhaltung der Gesetze.",
        "disc-h4": "4. Konforme Nutzung",
        "disc-p5": "Die Nutzung der App muss den Gesetzen Ihres Wohnsitzlandes entsprechen.",
        "disc-h5": "5. Marken Dritter",
        "disc-p6": "Alle erwähnten Marken gehören ihren jeweiligen Eigentümern."
    },
    es: {
        "nav-home": "Inicio",
        "nav-disclaimer": "Aviso Legal",
        "nav-privacy": "Privacidad",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Su Reproductor de Video Definitivo",
        "hero-subtitle": "Administre y reproduzca sus propias listas de reproducción (M3U, Xtream Codes) en una interfaz premium, diseñada para móviles y optimizada para Android TV.",
        "hero-btn-download": "Descargar la Aplicación",
        "hero-btn-privacy": "Política de Privacidad",
        "mockup-title": "Interfaz Cinemática Premium",
        "mockup-subtitle": "Inmersión visual total con historial de reproducción y navegación fluida con D-Pad.",
        "features-title": "Características Claves",
        "feat1-title": "Optimizado para Android TV",
        "feat1-desc": "Navegación fluida y completa con mando a distancia D-pad con vibración y animaciones para el salón.",
        "feat2-title": "Motor de Reproducción Rápido",
        "feat2-desc": "Decodificación de hardware ultra rápida para HLS y TS. Zapping fluido y pistas de audio/subtítulos.",
        "feat3-title": "Sincronización en la Nube",
        "feat3-desc": "Sincronice de forma segura sus favoritos e historial de reproducción con Firebase entre sus dispositivos.",
        "feat4-title": "Sin Contenido Incluido",
        "feat4-desc": "Una aplicación técnica 100% neutra y legal. No vendemos suscripciones. Usted tiene el control total de sus fuentes.",
        "download-title": "¿Listo para empezar?",
        "download-subtitle": "Instale IPTV Mediacenter en su teléfono, tableta, Android TV o Windows e importe su lista de reproducción.",
        "download-windows": "Descargar para Windows",
        "download-android": "Google Play Store",
        "download-support": "Contactar al Soporte",
        "download-discord": "Unirse al Discord",
        "footer-desc": "Este sitio web sirve como portal de soporte técnico y cumplimiento de normativas para tiendas de aplicaciones.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Todos los derechos reservados.",

        "privacy-title": "Política de Privacidad",
        "privacy-date": "Última actualización: 26 de abril de 2026",
        "privacy-p1": "IPTV Mediacenter (\"nosotros\", \"nuestro\" o \"la Aplicación\") se compromete a proteger su privacidad. Esta política explica cómo tratamos sus datos.",
        "privacy-h1": "1. Sin contenido proporcionado",
        "privacy-p2": "IPTV Mediacenter es un reproductor técnico. No proporcionamos ni alojamos canales o transmisiones. Los usuarios deben proveer su contenido.",
        "privacy-h2": "2. Recopilación de datos y privacidad",
        "privacy-p3": "Buscamos recopilar la menor cantidad de datos para respetar su privacidad:",
        "privacy-li1": "<strong>Almacenamiento local</strong>: Credenciales y listas guardadas en una base de datos local en su dispositivo.",
        "privacy-li2": "<strong>Sincronización</strong>: Firebase almacena opcionalmente sus favoritos e historial.",
        "privacy-li3": "<strong>ID del dispositivo</strong>: Usado técnicamente para mantener la estabilidad del streaming.",
        "privacy-li-sentry": "<strong>Informes de fallos y diagnóstico</strong>: Utilizamos <strong>Sentry</strong> (de Functional Software, Inc.) para recopilar registros de fallos anónimos e información de diagnóstico cuando la aplicación encuentra un error inesperado. Esto incluye detalles técnicos como el modelo del dispositivo, la versión del sistema operativo, la versión de la aplicación y el rastreo de la pila (stack trace). Estos datos se utilizan únicamente para mejorar la estabilidad y el rendimiento de la aplicación. No se envían datos personales a Sentry.",
        "privacy-li4": "<strong>Sin publicidad</strong>: No hay herramientas de seguimiento publicitario.",
        "privacy-li5": "<strong>Seguridad</strong>: Tránsito de datos encriptado vía HTTPS.",
        "privacy-h3": "3. Uso de la información",
        "privacy-p4": "Los datos sirven solo para reproducir el contenido, gestionar canales y sincronizar dispositivos.",
        "privacy-h4": "4. Terceros",
        "privacy-p5": "Utilizamos <strong>Firebase (Google)</strong> para la autentificación y sincronización en la nube, y <strong>Sentry</strong> para los informes de fallos. Además, su conexión se realiza directamente con los servidores de su proveedor IPTV, regulados por sus políticas de privacidad.",
        "privacy-h5": "5. Seguridad",
        "privacy-p6": "Uso de encriptación del sistema operativo.",
        "privacy-h6": "6. Menores",
        "privacy-p7": "No recopilamos datos de niños.",
        "privacy-h7": "7. Contacto",
        "privacy-p8": "Para dudas sobre la privacidad, escríbanos a:",

        "disc-title": "Aviso Legal",
        "disc-date": "Fecha de entrada en vigor: 26 de mayo de 2026",
        "disc-p1": "Este software es solo una herramienta de reproducción y no contiene ningún medio. Los usuarios deben suministrar sus fuentes.",
        "disc-h1": "1. Sin contenido multimedia",
        "disc-p2": "IPTV Mediacenter no provee canales ni películas. Es una herramienta neutral.",
        "disc-h2": "2. Sin afiliación",
        "disc-p3": "No tenemos relación con proveedores de servicios de IPTV. No vendemos planes.",
        "disc-h3": "3. Derechos de autor",
        "disc-p4": "No avalamos la reproducción de material protegido por derechos de autor sin permiso. El usuario es responsable legalmente de sus fuentes.",
        "disc-h4": "4. Uso lícito",
        "disc-p5": "El uso del software debe respetar las leyes de su país.",
        "disc-h5": "5. Marcas",
        "disc-p6": "Todas las marcas pertenecen a sus respectivos dueños."
    },
    it: {
        "nav-home": "Home",
        "nav-disclaimer": "Note Legali",
        "nav-privacy": "Privacy",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Il tuo Lettore Video Definitivo",
        "hero-subtitle": "Gestisci e riproduci facilmente le tue playlist (M3U, Xtream Codes) in un'interfaccia premium, progettata per dispositivi mobili e ottimizzata per Android TV.",
        "hero-btn-download": "Scarica l'App",
        "hero-btn-privacy": "Informativa sulla Privacy",
        "mockup-title": "Interfaccia Cinemashow Premium",
        "mockup-subtitle": "Immersione visiva completa con cronologia di riproduzione e navigazione fluida tramite D-Pad.",
        "features-title": "Caratteristiche Principali",
        "feat1-title": "Ottimizzato per Android TV",
        "feat1-desc": "Navigazione completa D-pad con feedback aptico e animazioni fluide per la tua TV.",
        "feat2-title": "Motore ExoPlayer Rapido",
        "feat2-desc": "Decodifica hardware ultra-rapida per flussi HLS e TS. Zapping fluido e gestione audio/sottotitoli.",
        "feat3-title": "Sincronizzazione Cloud",
        "feat3-desc": "Sincronizza in modo sicuro i tuoi preferiti e la cronologia con Firebase tra tutti i tuoi dispositivi.",
        "feat4-title": "Nessun Contenuto Incluso",
        "feat4-desc": "Applicazione tecnica neutra al 100%. Non forniamo abbonamenti. Mantieni il controllo totale delle tue fonti.",
        "download-title": "Pronto a iniziare?",
        "download-subtitle": "Installa IPTV Mediacenter su telefono, tablet, Android TV o Windows e importa la tua playlist.",
        "download-windows": "Scarica per Windows",
        "download-android": "Google Play Store",
        "download-support": "Contatta il Supporto",
        "download-discord": "Entra nel Discord",
        "footer-desc": "Questo sito Web funge da portale di supporto tecnico e conformità legale richiesto per le piattaforme di download.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Tutti i diritti riservati.",

        "privacy-title": "Informativa sulla Privacy",
        "privacy-date": "Ultimo aggiornamento: 26 aprile 2026",
        "privacy-p1": "IPTV Mediacenter (\"noi\", \"nostro\" o \"l'Applicazione\") si impegna a proteggere la tua privacy. Questa informativa spiega come trattiamo i tuoi dati.",
        "privacy-h1": "1. Nessun contenuto fornito",
        "privacy-p2": "L'applicazione è solo un lettore neutro. Non forniamo o ospitiamo flussi TV o film. L'utente deve caricare i propri contenuti.",
        "privacy-h2": "2. Raccolta dati",
        "privacy-p3": "Raccogliamo solo i dati strettamente necessari per rispettare la tua privacy:",
        "privacy-li1": "<strong>Archiviazione locale</strong>: Credenziali e playlist salvate in locale sul tuo dispositivo.",
        "privacy-li2": "<strong>Sincronizzazione cloud</strong>: Firebase gestisce la sincronizzazione di cronologia e preferiti.",
        "privacy-li3": "<strong>ID dispositivo</strong>: Utilizzato per scopi di stabilità dello streaming.",
        "privacy-li-sentry": "<strong>Segnalazione crash e diagnostica</strong>: Utilizziamo <strong>Sentry</strong> (di Functional Software, Inc.) per raccogliere registri di crash anonimi e informazioni diagnostiche quando l'applicazione riscontra un errore imprevisto. Ciò include dettagli tecnici come il modello del dispositivo, la versione del sistema operativo, la versione dell'applicazione e la traccia dello stack (stack trace). Utilizziamo questi dati esclusivamente per migliorare la stabilità e le prestazioni dell'app. Nessuna informazione di identificazione personale viene inviata a Sentry.",
        "privacy-li4": "<strong>Nessuna pubblicità</strong>: Non ci sono tracker pubblicitari di terze parti.",
        "privacy-li5": "<strong>Sicurezza</strong>: Trasferimenti cifrati tramite HTTPS.",
        "privacy-h3": "3. Uso delle informazioni",
        "privacy-p4": "I dati sono utilizzati solo per la riproduzione, la visualizzazione dei canali e la sincronizzazione.",
        "privacy-h4": "4. Servizi di terze parti",
        "privacy-p5": "Utilizziamo <strong>Firebase (Google)</strong> per l'autenticazione e la sincronizzazione cloud, e <strong>Sentry</strong> per la segnalazione dei crash. Inoltre, il dispositivo si connette direttamente ai server del tuo provider IPTV, regolati dalle loro politiche.",
        "privacy-h5": "5. Sicurezza",
        "privacy-p6": "Crittografia del sistema operativo attiva.",
        "privacy-h6": "6. Minori",
        "privacy-p7": "Non raccogliamo dati da bambini.",
        "privacy-h7": "7. Contatti",
        "privacy-p8": "Per domande sulla privacy, scrivici a:",

        "disc-title": "Note Legali",
        "disc-date": "Data di entrata in vigore: 26 maggio 2026",
        "disc-p1": "Questo software è solo uno strumento di riproduzione multimediale e non include alcun contenuto. Gli utenti devono fornire le proprie playlist.",
        "disc-h1": "1. Assenza di contenuti multimediali",
        "disc-p2": "L'app non offre canali o filmati. È uno strumento neutro.",
        "disc-h2": "2. Nessuna affiliazione",
        "disc-p3": "Non abbiamo legami con fornitori IPTV o distributori. Non vendiamo abbonamenti.",
        "disc-h3": "3. Diritto d'autore",
        "disc-p4": "Non supportiamo lo streaming di contenuti protetti da copyright senza autorizzazione. L'utente è responsabile delle proprie fonti.",
        "disc-h4": "4. Uso conforme",
        "disc-p5": "Rispettare le leggi del proprio paese durante l'uso dell'applicazione.",
        "disc-h5": "5. Marchi",
        "disc-p6": "Tutti i marchi appartengono ai rispettivi proprietari."
    },
    nl: {
        "nav-home": "Startpagina",
        "nav-disclaimer": "Disclaimer",
        "nav-privacy": "Privacybeleid",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Uw Ultieme Videospeler",
        "hero-subtitle": "Beheer en bekijk eenvoudig uw eigen afspeellijsten (M3U, Xtream Codes) in een premium interface, ontworpen voor mobiel en geoptimaliseerd voor Android TV.",
        "hero-btn-download": "App Downloaden",
        "hero-btn-privacy": "Privacybeleid",
        "mockup-title": "Premium Bioscoop Interface",
        "mockup-subtitle": "Volledige visuele immersie met geschiedenis en soepele navigatie via D-Pad.",
        "features-title": "Belangrijkste Kenmerken",
        "feat1-title": "Android TV Geoptimaliseerd",
        "feat1-desc": "Volledige afstandsbediening D-pad navigatie met voelbare trillingen en vloeiende animaties voor uw tv.",
        "feat2-title": "Snelle ExoPlayer Engine",
        "feat2-desc": "Ultrasnelle hardwaredecodering van HLS- en TS-stromen. Zappen zonder vertraging en ingebouwde audio/ondertitels.",
        "feat3-title": "Cloud Synchronisatie",
        "feat3-desc": "Synchroniseer uw favorieten en geschiedenis veilig via de Firebase-cloud tussen uw apparaten.",
        "feat4-title": "Geen Inhoud Inbegrepen",
        "feat4-desc": "Een 100% neutrale en legale technische toepassing. Wij verkopen geen abonnementen. U houdt controle over uw bronnen.",
        "download-title": "Klaar om te starten?",
        "download-subtitle": "Installeer IPTV Mediacenter op uw telefoon, tablet, Android TV of Windows en importeer uw afspeellijst.",
        "download-windows": "Download voor Windows",
        "download-android": "Google Play Store",
        "download-support": "Contact opnemen met Support",
        "download-discord": "Lid worden van Discord",
        "footer-desc": "Deze website dient als technisch ondersteunings- en juridisch nalevingsportaal vereist voor app-stores.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Alle rechten voorbehouden.",

        "privacy-title": "Privacybeleid",
        "privacy-date": "Laatst bijgewerkt: 26 april 2026",
        "privacy-p1": "IPTV Mediacenter (\"wij\", \"ons\" of \"de Applicatie\") streeft ernaar uw privacy te beschermen. Dit beleid legt uit hoe we uw gegevens verwerken.",
        "privacy-h1": "1. Geen inhoud geleverd",
        "privacy-p2": "IPTV Mediacenter is een neutrale speler. We leveren of hosten geen tv-zenders of media. Gebruikers moeten hun eigen afspeellijsten laden.",
        "privacy-h2": "2. Gegevensverzameling",
        "privacy-p3": "We verzamelen zo min mogelijk gegevens om uw privacy te waarborgen:",
        "privacy-li1": "<strong>Lokale opslag</strong>: Inloggegevens en kanalenlijst lokaal opgeslagen op uw apparaat.",
        "privacy-li2": "<strong>Synchronisatie</strong>: Firebase synchroniseert optioneel uw favorieten en geschiedenis.",
        "privacy-li3": "<strong>Apparaat-ID</strong>: Gebruikt om de stabiliteit van de videostream te waarborgen.",
        "privacy-li-sentry": "<strong>Crashrapportage & diagnostiek</strong>: We gebruiken <strong>Sentry</strong> (van Functional Software, Inc.) om anonieme crashrapporten en diagnostische informatie te verzamelen wanneer de app een onverwachte fout tegenkomt. Dit omvat technische details zoals apparaatmodel, OS-versie, applicatieversie en de stacktrace van de fout. We gebruiken deze gegevens uitsluitend om de stabiliteit en prestaties van de app te verbeteren. Er worden geen persoonlijk identificeerbare gegevens naar Sentry verzonden.",
        "privacy-li4": "<strong>Geen advertenties</strong>: We gebruiken geen ad-trackers.",
        "privacy-li5": "<strong>Beveiliging</strong>: Versleutelde gegevensoverdracht via HTTPS.",
        "privacy-h3": "3. Gebruik van informatie",
        "privacy-p4": "De gegevens worden alleen gebruikt om verbinding te maken, kanalen te tonen en uw voorkeuren te bewaren.",
        "privacy-h4": "4. Diensten van derden",
        "privacy-p5": "We gebruiken <strong>Firebase (Google)</strong> voor cloud-authenticatie en -synchronisatie, en <strong>Sentry</strong> voor crashrapportage. Bovendien maakt uw apparaat rechtstreeks verbinding met de servers van uw IPTV-aanbieder, die hun eigen beleid hebben.",
        "privacy-h5": "5. Beveiliging",
        "privacy-p6": "Standaard OS-versleuteling gebruikt.",
        "privacy-h6": "6. Privacy van kinderen",
        "privacy-p7": "We verzamelen geen gegevens van minderjarigen.",
        "privacy-h7": "7. Contact",
        "privacy-p8": "Bij vragen over privacy kunt u contact opnemen via:",

        "disc-title": "Disclaimer",
        "disc-date": "Ingangsdatum: 26 mei 2026",
        "disc-p1": "Deze software is uitsluitend een afspeeltool en bevat geen eigen media. Gebruikers moeten hun eigen afspeellijst aanleveren.",
        "disc-h1": "1. Geen media-inhoud",
        "disc-p2": "IPTV Mediacenter biedt geen kanalen of videobibliotheken. De app is een neutraal hulpmiddel.",
        "disc-h2": "2. Geen banden",
        "disc-p3": "We hebben geen relatie met IPTV-aanbieders en verkopen geen abonnementen.",
        "disc-h3": "3. Auteursrecht en piraterij",
        "disc-p4": "We keuren het streamen van auteursrechtelijk beschermd materiaal zonder toestemming af. De gebruiker is verantwoordelijk voor zijn bronnen.",
        "disc-h4": "4. Correct gebruik",
        "disc-p5": "Het gebruik van de app moet voldoen aan de wetgeving in uw land.",
        "disc-h5": "5. Handelsmerken",
        "disc-p6": "Alle merken behoren toe aan hun respectieve eigenaren."
    },
    ar: {
        "nav-home": "الرئيسية",
        "nav-disclaimer": "إخلاء المسؤولية",
        "nav-privacy": "الخصوصية",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>مشغل الفيديو المثالي لك",
        "hero-subtitle": "قم بإدارة وتشغيل قوائم التشغيل الخاصة بك (M3U ، Xtream Codes) بسهولة في واجهة مميزة، مصممة للهواتف ومتوافقة تماماً مع أجهزة Android TV.",
        "hero-btn-download": "تحميل التطبيق",
        "hero-btn-privacy": "سياسة الخصوصية",
        "mockup-title": "واجهة سينمائية ممتازة",
        "mockup-subtitle": "انغماس بصري كامل مع سجل للمشاهدة وتصفح سلس باستخدام جهاز التحكم.",
        "features-title": "الميزات الرئيسية",
        "feat1-title": "متوافق مع شاشات التلفاز",
        "feat1-desc": "تصفح كامل وسلس بجهاز التحكم عن بعد مع حركات وتأثيرات بصرية مصممة لراحتك.",
        "feat2-title": "مشغل ExoPlayer سريع",
        "feat2-desc": "فك ترميز سريع جداً لبث القنوات (HLS و TS) مع دعم التنقل السريع والترجمات ومسارات الصوت.",
        "feat3-title": "المزامنة السحابية",
        "feat3-desc": "قم بمزامنة قنواتك المفضلة وسجل المشاهدة بأمان عبر خوادم Firebase بين جميع أجهزتك.",
        "feat4-title": "لا يتضمن أي محتوى",
        "feat4-desc": "تطبيق تقني محايد وقانوني بنسبة 100%. نحن لا نقدم اشتراكات. أنت تحتفظ بالتحكم الكامل في مصادرك.",
        "download-title": "جاهز للبدء؟",
        "download-subtitle": "قم بتثبيت IPTV Mediacenter على هاتفك أو جهازك اللوحي أو شاشة التلفاز أو نظام Windows وابدأ بتشغيل قائمتك.",
        "download-windows": "تحميل لنظام Windows",
        "download-android": "متجر Google Play",
        "download-support": "الاتصال بالدعم",
        "download-discord": "الانضمام إلى ديسكورد",
        "footer-desc": "يعمل هذا الموقع كبوابة للدعم الفني والامتثال القانوني المطلوب للنشر في متاجر التطبيقات.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. جميع الحقوق محفوظة.",

        "privacy-title": "سياسة الخصوصية",
        "privacy-date": "آخر تحديث: 26 أبريل 2026",
        "privacy-p1": "يلتزم IPTV Mediacenter (\"نحن\" أو \"تطبيقنا\") بحماية خصوصيتك. توضح سياسة الخصوصية هذه كيفية التعامل مع بياناتك عند الاستخدام.",
        "privacy-h1": "1. لا نقدم أي محتوى",
        "privacy-p2": "التطبيق هو مجرد مشغل وسائط محايد. نحن لا نقدم أو نستضيف أي قنوات تلفزيونية أو بث مباشر. يجب على المستخدم توفير المحتوى الخاص به.",
        "privacy-h2": "2. جمع البيانات والخصوصية",
        "privacy-p3": "نحن نحرص على جمع أقل قدر ممكن من البيانات للحفاظ على خصوصيتك:",
        "privacy-li1": "<strong>التخزين المحلي</strong>: يتم حفظ جميع بيانات تسجيل الدخول وقوائم القنوات محلياً على جهازك في قاعدة بيانات آمنة.",
        "privacy-li2": "<strong>المزامنة السحابية</strong>: نستخدم خدمات Firebase لمزامنة المفضلة وسجل المشاهدة اختيارياً.",
        "privacy-li3": "<strong>معرفات الجهاز</strong>: قد نجمع بيانات تقنية عامة للحفاظ على استقرار تشغيل البث المباشر.",
        "privacy-li4": "<strong>لا توجد إعلانات</strong>: لا نستخدم أي أدوات تتبع إعلانية لأطراف خارجية.",
        "privacy-li5": "<strong>الأمان</strong>: يتم نقل جميع البيانات المشتركة مع السحابة بشكل مشفر عبر بروتوكول HTTPS الآمن.",
        "privacy-h3": "3. استخدام المعلومات",
        "privacy-p4": "تستخدم البيانات فقط للاتصال بالخادم الخاص بك وعرض دليل البرامج (EPG) ومزامنة تفضيلاتك.",
        "privacy-h4": "4. خدمات الطرف الثالث",
        "privacy-p5": "يتصل جهازك مباشرة بخوادم موزع الخدمة الخاص بك، وتخضع هذه الاتصالات لسياسة الخصوصية الخاصة بهم.",
        "privacy-h5": "5. الحماية والأمان",
        "privacy-p6": "نستخدم تقنيات التشفير القياسية المضمنة في نظام التشغيل لحماية بياناتك.",
        "privacy-h6": "6. خصوصية الأطفال",
        "privacy-p7": "تطبيقنا لا يجمع أي بيانات من الأطفال عن علم.",
        "privacy-h7": "7. اتصل بنا",
        "privacy-p8": "إذا كان لديك أي أسئلة حول الخصوصية، يمكنك التواصل معنا عبر البريد الإلكتروني:",

        "disc-title": "إخلاء المسؤولية القانونية",
        "disc-date": "تاريخ النفاذ: 26 مايو 2026",
        "disc-p1": "هذا البرنامج هو مجرد أداة لتشغيل الوسائط ولا يحتوي أو يوزع أي محتوى وسائط على الإطلاق. يجب على المستخدمين تقديم مصادرهم الخاصة.",
        "disc-h1": "1. خلو التطبيق من القنوات والمحتوى",
        "disc-p2": "لا يوفر IPTV Mediacenter أي قنوات تلفزيونية أو مكتبات أفلام. التطبيق أداة تقنية محايدة فقط.",
        "disc-h2": "2. عدم التبعية لأي جهة",
        "disc-p3": "ليس لدينا أي شراكة أو علاقة تجارية مع أي موزع قنوات أو اشتراكات IPTV. نحن لا نبيع أي اشتراكات.",
        "disc-h3": "3. حقوق النشر وحقوق الملكية",
        "disc-p4": "نحن لا ندعم تشغيل المواد المحمية بحقوق النشر دون إذن صاحب الحق. تقع المسؤولية الكاملة على المستخدم للتأكد من قانونية مصادره.",
        "disc-h4": "4. الاستخدام القانوني",
        "disc-p5": "يجب أن يتوافق استخدام التطبيق مع القوانين واللوائح السارية في بلد إقامتك.",
        "disc-h5": "5. العلامات التجارية",
        "disc-p6": "جميع العلامات التجارية والشعارات المذكورة هي ملك لأصحابها ولا تعني أي شراكة معنا."
    },
    pt: {
        "nav-home": "Página inicial",
        "nav-disclaimer": "Isenção de responsabilidade legal",
        "nav-privacy": "Política de Privacidade",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Seu reprodutor de vídeo definitivo",
        "hero-subtitle": "Gira e assista às suas próprias listas de reprodução (M3U, Xtream Codes) facilmente numa interface premium, desenhada para dispositivos móveis e otimizada para Android TV.",
        "hero-btn-download": "Descarregar App",
        "hero-btn-privacy": "Política de Privacidade",
        "mockup-title": "Interface Cinemática Premium",
        "mockup-subtitle": "Imersão visual total com histórico de reprodução e navegação fluida com comando D-Pad.",
        "features-title": "Funcionalidades Principais",
        "feat1-title": "Otimizado para Android TV",
        "feat1-desc": "Navegação D-pad remota completa com vibração e animações fluidas para o conforto da sua sala.",
        "feat2-title": "Motor ExoPlayer Rápido",
        "feat2-desc": "Descodificação de hardware ultra-rápida de fluxos HLS e TS. Zapping ultra-fluido e suporte para faixas de áudio/legendas integradas.",
        "feat3-title": "Sincronização na Nuvem",
        "feat3-desc": "Sincronize com segurança os seus favoritos e histórico de reprodução \"Continuar a assistir\" via Firebase entre os seus dispositivos.",
        "feat4-title": "Zero Conteúdo Incluído",
        "feat4-desc": "Uma aplicação técnica 100% neutra e legal. Não fornecemos qualquer subscrição. Mantém o controlo total das suas fontes.",
        "download-title": "Pronto para começar?",
        "download-subtitle": "Instale o IPTV Mediacenter no seu telemóvel, tablet, Android TV ou Windows e importe o seu primeiro fluxo de teste ou lista de reprodução pessoal.",
        "download-windows": "Descarregar para Windows",
        "download-android": "Google Play Store",
        "download-support": "Contactar o Suporte",
        "download-discord": "Aderir ao Discord",
        "footer-desc": "Este site serve como um portal de suporte técnico e conformidade legal necessário para o lançamento em lojas de aplicações.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Todos os direitos reservados.",

        "privacy-title": "Política de Privacidade",
        "privacy-date": "Última atualização: 26 de abril de 2026",
        "privacy-p1": "O IPTV Mediacenter (\"nós\", \"nosso\" ou \"a Aplicação\") está empenhado em proteger a sua privacidade. Esta política de privacidade explica como tratamos as suas informações quando utiliza a nossa aplicação móvel e Android TV.",
        "privacy-h1": "1. Nenhum Conteúdo Fornecido",
        "privacy-p2": "O IPTV Mediacenter é um reprodutor de média técnico. Não fornecemos, alojamos ou transmitimos qualquer conteúdo multimédia ou fluxos de TV. Os utilizadores devem fornecer as suas próprias fontes de conteúdo (por exemplo, listas de reprodução M3U obtidas legalmente ou credenciais de Xtream Codes). Não temos qualquer afiliação com fornecedores de conteúdo terceiros.",
        "privacy-h2": "2. Recolha de Dados e Respeito pela Privacidade",
        "privacy-p3": "Esforçamo-nos por recolher o mínimo de dados possível para garantir a sua privacidade:",
        "privacy-li1": "<strong>Armazenamento local</strong>: Todas as informações de início de sessão (URL do servidor, nome de utilizador, palavra-passe) e listas de canais são armazenadas <strong>localmente</strong> no seu dispositivo numa base de dados segura.",
        "privacy-li2": "<strong>Autenticação e sincronização na nuvem</strong>: A aplicação utiliza o Firebase Authentication e o Cloud Firestore (fornecidos pela Google) para permitir criar uma conta e sincronizar os seus <strong>Favoritos e Histórico de Reprodução</strong> entre os seus dispositivos.",
        "privacy-li3": "<strong>Identificadores de dispositivo</strong>: A aplicação pode recolher identificadores técnicos genéricos (modelo do dispositivo, versão do SO) para garantir a estabilidade do fluxo e respeitar os limites de ligações simultâneas do seu fornecedor.",
        "privacy-li4": "<strong>Nenhum rastreio publicitário</strong>: Não utilizamos quaisquer rastreadores publicitários de terceiros para analisar o seu comportamento dentro da aplicação.",
        "privacy-li5": "<strong>Transferências seguras</strong>: Todos os dados sincronizados com a nuvem são encriptados e transferidos de forma segura via HTTPS.",
        "privacy-h3": "3. Utilização da Informação",
        "privacy-p4": "As informações armazenadas localmente no seu dispositivo ou sincronizadas na sua conta segura na nuvem são utilizadas exclusivamente para:",
        "privacy-li6": "Ligar-se aos seus servidores de IPTV pessoais.",
        "privacy-li7": "Apresentar a sua lista de canais e o guia eletrónico de programas (EPG).",
        "privacy-li8": "Sincronizar os seus favoritos e retomar a reprodução de vídeo de um dispositivo para outro.",
        "privacy-h4": "4. Serviços de Terceiros",
        "privacy-p5": "Utilizamos o <strong>Firebase (Google)</strong> para autenticação e sincronização na nuvem, e o <strong>Sentry</strong> para relatórios de falhas. Além disso, quando adiciona um URL de lista de reprodução ou credenciais, o seu dispositivo liga-se diretamente aos servidores do seu fornecedor de IPTV, que são regidos pelas suas próprias políticas de privacidade. Não somos responsáveis pela forma como os seus dados são tratados por estes terceiros.",
        "privacy-h5": "5. Segurança",
        "privacy-p6": "Utilizamos métodos de encriptação padrão fornecidos pelo sistema operativo Android para proteger os seus dados de ligação armazenados no seu dispositivo.",
        "privacy-h6": "6. Privacidade das Crianças",
        "privacy-p7": "A nossa aplicação não recolhe intencionalmente dados pessoais de crianças.",
        "privacy-h7": "7. Contacto",
        "privacy-p8": "Se tiver alguma dúvida sobre esta Política de Privacidade, pode contactar-nos por e-mail em:",

        "disc-title": "Isenção de Responsabilidade Legal e Não-Responsabilidade",
        "disc-date": "Data de Entrada em Vigor: 26 de maio de 2026",
        "disc-p1": "Este software é estritamente uma ferramenta de reprodução multimédia e não fornece, distribui ou contém qualquer conteúdo multimédia de qualquer tipo. Os utilizadores devem fornecer as suas próprias fontes (listas de reprodução M3U, credenciais de servidor Xtream Codes, etc.).",
        "disc-h1": "1. Ausência de Conteúdo Multimédia",
        "disc-p2": "O IPTV Mediacenter não fornece quaisquer fluxos de vídeo, canais de TV ou bibliotecas de filmes e séries. A aplicação é uma ferramenta neutra que descodifica e apresenta as listas de reprodução introduzidas voluntariamente pelo utilizador.",
        "disc-h2": "2. Ausência de Afiliação Legal",
        "disc-p3": "O IPTV Mediacenter não tem qualquer afiliação, parceria ou ligação comercial com fornecedores de fluxos, revendedores de subscrições ou distribuidores de conteúdos IPTV. Não vendemos subscrições ou acesso a média.",
        "disc-h3": "3. Direitos de Autor e Pirataria",
        "disc-p4": "Não apoiamos nem toleramos a transmissão ou reprodução de material protegido por direitos de autor sem a autorização explícita do detentor dos direitos. É da estrita responsabilidade do utilizador garantir que as suas fontes de transmissão de IPTV cumprem as regulamentações locais e internacionais vigentes. O IPTV Mediacenter não pode ser responsabilizado pela utilização não autorizada do software para reproduzir conteúdos piratas.",
        "disc-h4": "4. Utilização Conforme",
        "disc-p5": "A utilização da nossa aplicação deve cumprir estritamente as leis do seu país de residência. Qualquer utilização ilícita do software é da exclusiva responsabilidade do utilizador final.",
        "disc-h5": "5. Marcas Registadas de Terceiros",
        "disc-p6": "Todos os logótipos, nomes de produtos ou marcas registadas mencionados na documentação ou na apresentação pertencem aos seus respetivos proprietários e de forma alguma constituem um endosso ou parceria da sua parte.",

        "faq-title": "Perguntas Frequentes (FAQ)",
        "faq-q1": "O que é o IPTV Mediacenter?",
        "faq-a1": "O IPTV Mediacenter é um reprodutor multimédia gratuito e neutro. Permite-lhe ver as suas próprias listas de reprodução (M3U, Xtream Codes) com uma interface de utilizador otimizada para TV e telemóvel.",
        "faq-q2": "A aplicação fornece canais ou subscrições?",
        "faq-a2": "Não. O IPTV Mediacenter não fornece quaisquer fluxos de vídeo, canais de TV ou subscrições. Deve configurar e importar as suas próprias fontes de transmissão legais.",
        "faq-q3": "Em que dispositivos posso instalar a aplicação?",
        "faq-a3": "A aplicação está otimizada para Android TV (com navegação completa por comando), smartphones/tablets Android e Windows (descarregável na Microsoft Store)."
    },
    tr: {
        "nav-home": "Ana Sayfa",
        "nav-disclaimer": "Yasal Uyarı",
        "nav-privacy": "Gizlilik Politikası",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Gelişmiş Video Oynatıcınız",
        "hero-subtitle": "Kendi oynatma listelerinizi (M3U, Xtream Codes) mobil için tasarlanmış ve Android TV için optimize edilmiş premium bir arayüzde kolayca yönetin ve izleyin.",
        "hero-btn-download": "Uygulamayı İndir",
        "hero-btn-privacy": "Gizlilik Politikası",
        "mockup-title": "Premium Sinematik Arayüz",
        "mockup-subtitle": "İzleme geçmişi ve D-Pad ile akıcı navigasyon sayesinde tam görsel deneyim.",
        "features-title": "Temel Özellikler",
        "feat1-title": "Android TV Uyumlu",
        "feat1-desc": "Oturma odanızın konforu için dokunsal geri bildirim ve akıcı animasyonlara sahip tam D-pad kumanda navigasyonu.",
        "feat2-title": "Hızlı ExoPlayer Motoru",
        "feat2-desc": "HLS ve TS akışları için ultra hızlı donanım kod çözme. Kesintisiz kanal geçişi ve gömülü ses/altyazı parçası desteği.",
        "feat3-title": "Bulut Senkronizasyonu",
        "feat3-desc": "Favorilerinizi ve \"İzlemeye Devam Et\" geçmişinizi Firebase bulut altyapısı üzerinden cihazlarınız arasında güvenli bir şekilde senkronize edin.",
        "feat4-title": "İçerik Barındırmaz",
        "feat4-desc": "%100 tarafsız ve yasal teknik uygulama. Abonelik satmıyoruz veya sağlamıyoruz. Yayın kaynaklarınızın kontrolü tamamen sizdedir.",
        "download-title": "Başlamaya Hazır mısınız?",
        "download-subtitle": "IPTV Mediacenter'ı telefonunuza, tabletinize, Android TV'nize veya Windows cihazınıza kurun ve ilk test akışınızı veya kişisel oynatma listenizi içe aktarın.",
        "download-windows": "Windows için İndir",
        "download-android": "Google Play Store",
        "download-support": "Destekle İletişime Geçin",
        "download-discord": "Discord Sunucumuza Katılın",
        "footer-desc": "Bu web sitesi, uygulama mağazalarında yayınlanmak için gerekli olan teknik destek ve yasal uyumluluk portalı olarak hizmet vermektedir.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Tüm hakları saklıdır.",

        "privacy-title": "Gizlilik Politikası",
        "privacy-date": "Son güncelleme: 26 Nisan 2026",
        "privacy-p1": "IPTV Mediacenter (\"biz\", \"bize\" veya \"Uygulama\") gizliliğinizi korumayı taahhüt eder. Bu gizlilik politikası, mobil ve Android TV uygulamamızı kullandığınızda bilgilerinizi nasıl işlediğimizi açıklar.",
        "privacy-h1": "1. İçerik Sağlanmaz",
        "privacy-p2": "IPTV Mediacenter teknik bir medya oynatıcıdır. Herhangi bir multimedya içeriği veya TV yayını sağlamayız, barındırmayız veya akışını yapmayız. Kullanıcılar kendi içerik kaynaklarını (örneğin yasal olarak elde edilmiş M3U oynatma listelerini veya Xtream Codes bilgilerini) sağlamalıdır. Herhangi bir üçüncü taraf içerik sağlayıcısıyla bağlantımız yoktur.",
        "privacy-h2": "2. Veri Toplama ve Gizliliğe Saygı",
        "privacy-p3": "Gizliliğinizi garanti altına almak için mümkün olduğunca az veri toplamaya çalışıyoruz:",
        "privacy-li1": "<strong>Yerel depolama</strong>: Tüm giriş bilgileri (sunucu URL'si, kullanıcı adı, şifre) ve kanal listeleri cihazınızda güvenli bir veri tabanında <strong>yerel olarak</strong> saklanır.",
        "privacy-li2": "<strong>Kimlik doğrulama ve bulut senkronizasyonu</strong>: Uygulama, cihazlarınız arasında <strong>Favorilerinizi ve İzleme Geçmişinizi</strong> senkronize etmenize ve bir hesap oluşturmanıza olanak tanımak için Firebase Authentication ve Cloud Firestore (Google tarafından sağlanan) hizmetlerini kullanır.",
        "privacy-li3": "<strong>Cihaz tanımlayıcıları</strong>: Uygulama, akış kararlılığını sağlamak ve sağlayıcınızın eş zamanlı bağlantı sınırlarına uymak için genel teknik tanımlayıcıları (cihaz modeli, işletim sistemi sürümü) toplayabilir.",
        "privacy-li-sentry": "<strong>Kilitlenme Raporlama ve Teşhis</strong>: Uygulama beklenmeyen bir hatayla karşılaştığında anonim kilitlenme günlüklerini ve teşhis bilgilerini toplamak için <strong>Sentry</strong> (Functional Software, Inc. tarafından) kullanıyoruz. Bu, cihaz modeli, işletim sistemi sürümü, uygulama sürümü ve hatanın yığın izi (stack trace) gibi teknik ayrıntıları içerir. Bu verileri yalnızca uygulamanın kararlılığını ve performansını artırmak için kullanıyoruz. Sentry'ye hiçbir kişisel olarak tanımlanabilir bilgi gönderilmez.",
        "privacy-li4": "<strong>Reklam takibi yapılmaz</strong>: Uygulama içindeki davranışlarınızı analiz etmek için hiçbir üçüncü taraf reklam takip aracı kullanmayız.",
        "privacy-li5": "<strong>Güvenli veri transferi</strong>: Bulutla senkronize edilen tüm veriler şifrelenir ve HTTPS protokolü üzerinden güvenli bir şekilde aktarılır.",
        "privacy-h3": "3. Bilgilerin Kullanımı",
        "privacy-p4": "Cihazınızda yerel olarak saklanan veya güvenli bulut hesabınızla senkronize edilen bilgiler yalnızca şu amaçlarla kullanılır:",
        "privacy-li6": "Kişisel IPTV sunucularınıza bağlanmak.",
        "privacy-li7": "Kanal listenizi ve elektronik program rehberini (EPG) görüntülemek.",
        "privacy-li8": "Favorilerinizi senkronize etmek ve video oynatmayı bir cihazdan diğerine devam ettirmek.",
        "privacy-h4": "4. Üçüncü Taraf Hizmetleri",
        "privacy-p5": "Bulut kimlik doğrulama ve senkronizasyon için <strong>Firebase (Google)</strong>, kilitlenme raporlama için ise <strong>Sentry</strong> kullanıyoruz. Ayrıca, bir oynatma listesi URL'si veya kimlik bilgileri eklediğinizde, cihazınız doğrudan IPTV sağlayıcınızın kendi gizlilik politikalarına tabi olan üçüncü taraf sunucularına bağlanır.",
        "privacy-h5": "5. Güvenlik",
        "privacy-p6": "Cihazınızda saklanan bağlantı verilerinizi korumak için Android işletim sistemi tarafından sağlanan standart şifreleme yöntemlerini kullanıyoruz.",
        "privacy-h6": "6. Çocukların Gizliliği",
        "privacy-p7": "Uygulamamız bilerek çocuklardan kişisel veri toplamaz.",
        "privacy-h7": "7. İletişim",
        "privacy-p8": "Bu Gizlilik Politikası ile ilgili herhangi bir sorunuz varsa, bize e-posta yoluyla şu adresten ulaşabilirsiniz:",

        "disc-title": "Yasal Uyarı ve Sorumluluk Reddi",
        "disc-date": "Yürürlük Tarihi: 26 Mayıs 2026",
        "disc-p1": "Bu yazılım kesinlikle bir medya oynatma aracıdır ve hiçbir şekilde hiçbir medya içeriği sağlamaz, dağıtmaz veya içermez. Kullanıcılar kendi kaynaklarını (M3U oynatma listeleri, Xtream Codes sunucu bilgileri vb.) kendileri sağlamalıdır.",
        "disc-h1": "1. Multimedya İçerik Bulunmaması",
        "disc-p2": "IPTV Mediacenter herhangi bir video akışı, TV kanalı veya film/dizi kitaplığı sağlamaz. Uygulama, kullanıcı tarafından gönüllü olarak girilen oynatma listelerini çözen ve görüntüleyen tarafsız bir araçtır.",
        "disc-h2": "2. Yasal Bağlantı Olmaması",
        "disc-p3": "IPTV Mediacenter'ın yayın sağlayıcıları, abonelik bayileri veya IPTV içerik dağıtıcıları ile hiçbir ilişkisi, ortaklığı veya ticari bağı yoktur. Abonelik veya medya erişimi satmıyoruz.",
        "disc-h3": "3. Telif Hakkı ve Korsanlık",
        "disc-p4": "Telif hakkı sahibinin açık izni olmadan telif hakkıyla korunan materyallerin yayınlanmasını veya oynatılmasını desteklemiyoruz ve buna hoşgörü göstermiyoruz. IPTV yayın kaynaklarının yürürlükteki yerel ve uluslararası düzenlemelere uygun olmasını sağlamak tamamen kullanıcının sorumluluğundadır. IPTV Mediacenter, yazılımın korsan içerikleri oynatmak amacıyla yetkisiz kullanımından sorumlu tutulamaz.",
        "disc-h4": "4. Uyumlu Kullanım",
        "disc-p5": "Uygulamamızın kullanımı, ikamet ettiğiniz ülkenin yasalarına kesinlikle uygun olmalıdır. Yazılımın her türlü yasa dışı kullanımı tamamen son kullanıcının sorumluluğundadır.",
        "disc-h5": "5. Üçüncü Taraf Ticari Markaları",
        "disc-p6": "Belgelerde veya sunumda adı geçen tüm logolar, ürün adları veya ticari markalar kendi sahiplerine aittir ve hiçbir şekilde onlar tarafından onaylandığımız veya ortaklığımız olduğu anlamına gelmez.",

        "faq-title": "Sıkça Sorulan Sorular (SSS)",
        "faq-q1": "IPTV Mediacenter nedir?",
        "faq-a1": "IPTV Mediacenter ücretsiz ve tarafsız bir medya oynatıcıdır. Televizyon ve mobil cihazlar için optimize edilmiş bir kullanıcı arayüzü ile kendi oynatma listelerinizi (M3U, Xtream Codes) izlemenizi sağlar.",
        "faq-q2": "Uygulama kanal veya abonelik sağlıyor mu?",
        "faq-a2": "Hayır. IPTV Mediacenter herhangi bir video akışı, TV kanalı veya abonelik sağlamaz. Kendi yasal yayın kaynaklarınızı yapılandırmalı ve içe aktarmalısınız.",
        "faq-q3": "Uygulamayı hangi cihazlara yükleyebilirim?",
        "faq-a3": "Uygulama; Android TV (tam uzaktan kumanda navigasyonu ile), Android akıllı telefonlar/tabletler ve Windows (Microsoft Store'dan indirilebilir) için optimize edilmiştir."
    },
    el: {
        "nav-home": "Σπίτι",
        "nav-disclaimer": "Νομική Αποποίηση Ευθύνης",
        "nav-privacy": "Πολιτική Απορρήτου",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Το Απόλυτο Πρόγραμμα Αναπαραγωγής Βίντεο",
        "hero-subtitle": "Διαχειριστείτε και παρακολουθήστε τις δικές σας λίστες αναπαραγωγής (M3U, Xtream Codes) εύκολα σε ένα premium περιβάλλον εργασίας, σχεδιασμένο για κινητά και βελτιστοποιημένο για Android TV.",
        "hero-btn-download": "Λήψη Εφαρμογής",
        "hero-btn-privacy": "Πολιτική Απορρήτου",
        "mockup-title": "Κορυφαίο Κινηματογραφικό Περιβάλλον Εργασίας",
        "mockup-subtitle": "Πλήρης οπτική εμπειρία με ιστορικό προβολής και ομαλή πλοήγηση με D-Pad.",
        "features-title": "Βασικά Χαρακτηριστικά",
        "feat1-title": "Βελτιστοποιημένο για Android TV",
        "feat1-desc": "Πλήρης πλοήγηση με τηλεχειριστήριο D-pad με απτική ανάδραση και ομαλά γραφικά για την άνεση του σαλονιού σας.",
        "feat2-title": "Γρήγορη Μηχανή ExoPlayer",
        "feat2-desc": "Εξαιρετικά γρήγορη αποκωδικοποίηση υλικού για ροές HLS και TS. Ομαλή αλλαγή καναλιών (zapping) και υποστήριξη για ενσωματωμένα κομμάτια ήχου/υποτίτλων.",
        "feat3-title": "Συγχρονισμός Cloud",
        "feat3-desc": "Συγχρονίστε με ασφάλεια τα αγαπημένα σας και το ιστορικό \"Συνέχεια παρακολούθησης\" μέσω της υποδομής cloud του Firebase μεταξύ των συσκευών σας.",
        "feat4-title": "Δεν Περιλαμβάνεται Περιεχόμενο",
        "feat4-desc": "Μια 100% ουδέτερη και νόμιμη τεχνική εφαρμογή. Δεν παρέχουμε συνδρομές. Διατηρείτε τον πλήρη έλεγχο των πηγών σας.",
        "download-title": "Έτοιμοι να ξεκινήσετε;",
        "download-subtitle": "Εγκαταστήστε το IPTV Mediacenter στο τηλέφωνο, το tablet, το Android TV ή τα Windows και εισαγάγετε την πρώτη σας δοκιμαστική ροή ή την προσωπική σας λίστα αναπαραγωγής.",
        "download-windows": "Λήψη για Windows",
        "download-android": "Google Play Store",
        "download-support": "Επικοινωνία με την Υποστήριξη",
        "download-discord": "Γίνετε μέλος στο Discord",
        "footer-desc": "Αυτός ο ιστότοπος χρησιμεύει ως πύλη τεχνικής υποστήριξης και νομικής συμμόρφωσης που απαιτείται για την ανάπτυξη σε καταστήματα εφαρμογών.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Με την επιφύλαξη παντός δικαιώματος.",

        "privacy-title": "Πολιτική Απορρήτου",
        "privacy-date": "Τελευταία ενημέρωση: 26 Μαΐου 2026",
        "privacy-p1": "Το IPTV Mediacenter (\"εμείς\", \"εμάς\" ή \"η Εφαρμογή\") δεσμεύεται να προστατεύει το απόρρητό σας. Αυτή η πολιτική απορρήτου εξηγεί πώς χειριζόμαστε τις πληροφορίες σας όταν χρησιμοποιείτε την εφαρμογή μας για κινητά και Android TV.",
        "privacy-h1": "1. Δεν παρέχεται περιεχόμενο",
        "privacy-p2": "Το IPTV Mediacenter είναι ένα τεχνικό πρόγραμμα αναπαραγωγής πολυμέσων. Δεν παρέχουμε, φιλοξενούμε ή μεταδίδουμε κανένα περιεχόμενο πολυμέσων ή τηλεοπτικές ροές. Οι χρήστες πρέπει να παρέχουν τις δικές τους πηγές περιεχομένου (π.χ. λίστες αναπαραγωγής M3U που έχουν αποκτηθεί νόμιμα ή διαπιστευτήρια Xtream Codes). Δεν έχουμε καμία σχέση με τρίτους παρόχους περιεχομένου.",
        "privacy-h2": "2. Συλλογή Δεδομένων και Σεβασμός του Απορρήτου",
        "privacy-p3": "Προσπαθούμε να συλλέγουμε όσο το δυνατόν λιγότερα δεδομένα για να εγγυηθούμε το απόρρητό σας:",
        "privacy-li1": "<strong>Τοπική αποθήκευση</strong>: Όλες οι πληροφορίες σύνδεσης (URL διακομιστή, όνομα χρήστη, κωδικός πρόσβασης) και οι λίστες καναλιών αποθηκεύονται <strong>τοπικά</strong> στη συσκευή σας σε μια ασφαλή βάση δεδομένων.",
        "privacy-li2": "<strong>Έλεγχος ταυτότητας και συγχρονισμός cloud</strong>: Η εφαρμογή χρησιμοποιεί το Firebase Authentication και το Cloud Firestore (παρέχονται από την Google) για να σας επιτρέψει να δημιουργήσετε έναν λογαριασμό και να συγχρονίσετε τα <strong>Αγαπημένα και το Ιστορικό Αναπαραγωγής</strong> μεταξύ των συσκευών σας.",
        "privacy-li3": "<strong>Αναγνωριστικά συσκευής</strong>: Η εφαρμογή ενδέχεται να συλλέγει γενικά τεχνικά αναγνωριστικά (μοντέλο συσκευής, έκδοση λειτουργικού συστήματος) για να διασφαλίσει τη σταθερότητα της ροής και να σεβαστεί τα όρια ταυτόχρονης σύνδεσης του παρόχου σας.",
        "privacy-li-sentry": "<strong>Αναφορά σφαλμάτων & Διαγνωστικά</strong>: Χρησιμοποιούμε το <strong>Sentry</strong> (από τη Functional Software, Inc.) για τη συλλογή ανώνυμων καταγραφών σφαλμάτων και διαγνωστικών πληροφοριών όταν η εφαρμογή αντιμετωπίζει ένα απροσδόκητο σφάλμα. Αυτό περιλαμβάνει τεχνικές λεπτομέρειες όπως το μοντέλο συσκευής, την έκδοση του λειτουργικού συστήματος, την έκδοση της εφαρμογής και το stack trace του σφάλματος. Χρησιμοποιούμε αυτά τα δεδομένα αποκλειστικά για τη βελτίωση της σταθερότητας και της απόδοσης της εφαρμογής. Καμία προσωπικά ταυτοποιήσιμη πληροφορία δεν στέλνεται στο Sentry.",
        "privacy-li4": "<strong>Όχι παρακολούθηση διαφημίσεων</strong>: Δεν χρησιμοποιούμε trackers διαφημίσεων τρίτων για να αναλύσουμε τη συμπεριφορά σας εντός της εφαρμογής.",
        "privacy-li5": "<strong>Ασφαλείς μεταφορές</strong>: Όλα τα δεδομένα που συγχρονίζονται με το cloud είναι κρυπτογραφημένα και μεταφέρονται με ασφάλεια μέσω HTTPS.",
        "privacy-h3": "3. Χρήση των Πληροφοριών",
        "privacy-p4": "Οι πληροφορίες που αποθηκεύονται τοπικά στη συσκευή σας ή συγχρονίζονται στον ασφαλή λογαριασμό σας στο cloud χρησιμοποιούνται αποκλειστικά για:",
        "privacy-li6": "Σύνδεση στους προσωπικούς σας διακομιστές IPTV.",
        "privacy-li7": "Εμφάνιση της λίστας καναλιών σας και του ηλεκτρονικού οδηγού προγραμμάτων (EPG).",
        "privacy-li8": "Συγχρονισμό των αγαπημένων σας και συνέχιση της αναπαραγωγής βίντεο από τη μία συσκευή στην άλλη.",
        "privacy-h4": "4. Υπηρεσίες Τρίτων",
        "privacy-p5": "Όταν προσθέτετε μια διεύθυνση URL λίστας αναπαραγωγής ή διαπιστευτήρια, η συσκευή σας συνδέεται απευθείας με τους διακομιστές τρίτων του παρόχου σας IPTV. Αυτοί οι εξωτερικοί διακομιστές διέπονται από τις δικές τους πολιτικές απορρήτου. Δεν φέρουμε ευθύνη για τον τρόπο με τον οποίο τα δεδομένα σας αντιμετωπίζονται από αυτά τα τρίτα μέρη.",
        "privacy-h5": "5. Ασφάλεια",
        "privacy-p6": "Χρησιμοποιούμε τυπικές μεθόδους κρυπτογράφησης που παρέχονται από το λειτουργικό σύστημα Android για την προστασία των δεδομένων σύνδεσής σας που αποθηκεύονται στη συσκευή σας.",
        "privacy-h6": "6. Απόρρητο των Παιδιών",
        "privacy-p7": "Η εφαρμογή μας δεν συλλέγει εν γνώσει της προσωπικά δεδομένα από παιδιά.",
        "privacy-h7": "7. Επικοινωνία",
        "privacy-p8": "Εάν έχετε οποιεσδήποτε ερωτήσεις σχετικά με αυτήν την Πολιτική Απορρήτου, μπορείτε να επικοινωνήσετε μαζί μας μέσω email στη διεύθυνση:",

        "disc-title": "Νομική Αποποίηση Ευθύνης και Μη Ευθύνη",
        "disc-date": "Ημερομηνία Έναρξης Ισχύος: 26 Μαΐου 2026",
        "disc-p1": "Αυτό το λογισμικό είναι αυστηρά ένα εργαλείο αναπαραγωγής πολυμέσων και δεν παρέχει, διανέμει ή περιέχει κανένα περιεχόμενο πολυμέσων οποιουδήποτε είδους. Οι χρήστες πρέπει να παρέχουν τις δικές τους πηγές (λίστες αναπαραγωγής M3U, διαπιστευτήρια διακομιστή Xtream Codes κ.λπ.).",
        "disc-h1": "1. Απουσία Περιεχομένου Πολυμέσων",
        "disc-p2": "Το IPTV Mediacenter δεν παρέχει ροές βίντεο, τηλεοπτικά κανάλια ή βιβλιοθήκες ταινιών και σειρών. Η εφαρμογή είναι ένα ουδέτερο εργαλείο που αποκωδικοποιεί και εμφανίζει τις λίστες αναπαραγωγής που εισάγονται οικειοθελώς από τον χρήστη.",
        "disc-h2": "2. Απουσία Νομικής Σύνδεσης",
        "disc-p3": "Το IPTV Mediacenter δεν έχει καμία σχέση, συνεργασία ή εμπορικό σύνδεσμο με παρόχους ροής, μεταπωλητές συνδρομών ή διανομείς περιεχομένου IPTV. Δεν πουλάμε συνδρομές ή πρόσβαση σε μέσα.",
        "disc-h3": "3. Πνευματικά Δικαιώματα και Πειρατεία",
        "disc-p4": "Δεν υποστηρίζουμε ούτε ανεχόμαστε τη μετάδοση ή την αναπαραγωγή υλικού που προστατεύεται από πνευματικά δικαιώματα χωρίς τη ρητή άδεια του κατόχου των πνευματικών δικαιωμάτων. Είναι αποκλειστική ευθύνη του χρήστη να διασφαλίσει ότι οι πηγές ροής IPTV συμμορφώνονται με τους ισχύοντες τοπικούς και διεθνείς κανονισμούς. Το IPTV Mediacenter δεν μπορεί να θεωρηθεί υπεύθυνο για τη μη εξουσιοδοτημένη χρήση του λογισμικού για την αναπαραγωγή πειρατικού περιεχομένου.",
        "disc-h4": "4. Συμβατή Χρήση",
        "disc-p5": "Η χρήση της εφαρμογής μας πρέπει να συμμορφώνεται αυστηρά με τους νόμους της χώρας διαμονής σας. Οποιαδήποτε παράνομη χρήση του λογισμικού είναι αποκλειστική ευθύνη του τελικού χρήστη.",
        "disc-h5": "5. Εμπορικά Σήματα Τρίτων",
        "disc-p6": "Όλα τα λογότυπα, τα ονόματα προϊόντων ή τα εμπορικά σήματα που αναφέρονται στην τεκμηρίωση ή την παρουσίαση ανήκουν στους αντίστοιχους κατόχους τους και σε καμία περίπτωση δεν αποτελούν έγκριση ή συνεργασία από μέρους τους.",

        "faq-title": "Συχνές Ερωτήσεις (FAQ)",
        "faq-q1": "Τι είναι το IPTV Mediacenter;",
        "faq-a1": "Το IPTV Mediacenter είναι ένα δωρεάν και ουδέτερο πρόγραμμα αναπαραγωγής πολυμέσων. Σας επιτρέπει να παρακολουθείτε τις δικές σας λίστες αναπαραγωγής (M3U, Xtream Codes) με ένα περιβάλλον εργασίας χρήστη βελτιστοποιημένο για τηλεόραση και κινητά.",
        "faq-q2": "Παρέχει η εφαρμογή κανάλια ή συνδρομές;",
        "faq-a2": "Όχι. Το IPTV Mediacenter δεν παρέχει ροές βίντεο, τηλεοπτικά κανάλια ή συνδρομές. Πρέπει να διαμορφώσετε και να εισαγάγετε τις δικές σας νόμιμες πηγές ροής.",
        "faq-q3": "Σε ποιες συσκευές μπορώ να εγκαταστήσω την εφαρμογή;",
        "faq-a3": "Η εφαρμογή είναι βελτιστοποιημένη για Android TV (με πλήρη πλοήγηση μέσω τηλεχειριστηρίου), smartphone/tablet Android και Windows (με δυνατότητα λήψης από το Microsoft Store)."
    },
    ro: {
        "nav-home": "Acasă",
        "nav-disclaimer": "Declinarea răspunderii legale",
        "nav-privacy": "Politica de confidențialitate",
        "hero-title": "<span class=\"gradient-text\">IPTV Mediacenter</span><br>Playerul tău video suprem",
        "hero-subtitle": "Gestionați și vizionați cu ușurință propriile liste de redare (M3U, Xtream Codes) într-o interfață premium, concepută pentru dispozitive mobile și optimizată pentru Android TV.",
        "hero-btn-download": "Descărcați aplicația",
        "hero-btn-privacy": "Politica de confidențialitate",
        "mockup-title": "Interfață cinematografică premium",
        "mockup-subtitle": "Imersiune vizuală completă cu istoricul de vizionare și navigare fluidă prin D-Pad.",
        "features-title": "Caracteristici cheie",
        "feat1-title": "Optimizat pentru Android TV",
        "feat1-desc": "Navigare completă prin telecomandă D-pad cu feedback haptic și animații fluide pentru confortul sufrageriei tale.",
        "feat2-title": "Motor ExoPlayer rapid",
        "feat2-desc": "Decodare hardware ultra-rapidă pentru fluxurile HLS și TS. Zapping fără întreruperi și suport pentru piste audio/subtitrări integrate.",
        "feat3-title": "Sincronizare în cloud",
        "feat3-desc": "Sincronizați în siguranță favoritele și istoricul „Continuați vizionarea” prin infrastructura Firebase cloud între dispozitivele dvs.",
        "feat4-title": "Niciun conținut inclus",
        "feat4-desc": "O aplicație tehnică 100% neutră și legală. Nu oferim abonamente. Păstrați controlul complet asupra surselor dumneavoastră.",
        "download-title": "Sunteți gata să începeți?",
        "download-subtitle": "Instalați IPTV Mediacenter pe telefon, tabletă, Android TV sau Windows și importați primul flux de test sau playlist personal.",
        "download-windows": "Descărcați pentru Windows",
        "download-android": "Google Play Store",
        "download-support": "Contactați asistența",
        "download-discord": "Alăturați-vă serverului Discord",
        "footer-desc": "Acest site web servește ca un portal de asistență tehnică și conformitate legală necesar pentru implementarea în magazinele de aplicații.",
        "footer-copyright": "&copy; 2026 IPTV Mediacenter. Toate drepturile rezervate.",

        "privacy-title": "Politica de confidențialitate",
        "privacy-date": "Ultima actualizare: 26 aprilie 2026",
        "privacy-p1": "IPTV Mediacenter („noi”, „nostru” sau „Aplicația”) se angajează să vă protejeze confidențialitatea. Această politică de confidențialitate explică modul în care vă gestionăm informațiile atunci când utilizați aplicația noastră pentru mobil și Android TV.",
        "privacy-h1": "1. Niciun conținut furnizat",
        "privacy-p2": "IPTV Mediacenter este un player media tehnic. Nu furnizăm, găzduim și nu transmitem niciun conținut multimedia sau fluxuri TV. Utilizatorii trebuie să își asigure propriile surse de conținut (de exemplu, liste de redare M3U obținute legal sau acreditări Xtream Codes). Nu avem nicio afiliere cu furnizori de conținut terți.",
        "privacy-h2": "2. Colectarea datelor și respectul pentru confidențialitate",
        "privacy-p3": "Ne străduim să colectăm cât mai puține date pentru a vă garanta confidențialitatea:",
        "privacy-li1": "<strong>Stocare locală</strong>: Toate informațiile de conectare (URL server, nume utilizator, parolă) și listele de canale sunt stocate <strong>local</strong> pe dispozitivul dvs. într o bază de date securizată.",
        "privacy-li2": "<strong>Autentificare și sincronizare în cloud</strong>: Aplicația utilizează Firebase Authentication și Cloud Firestore (furnizate de Google) pentru a vă permite să creați un cont și să vă sincronizați <strong>Favoritele și Istoricul de redare</strong> pe toate dispozitivele.",
        "privacy-li3": "<strong>Identificatori de dispozitiv</strong>: Aplicația poate colecta identificatori tehnici generici (model de dispozitiv, versiune sistem de operare) pentru a asigura stabilitatea fluxului și pentru a respecta limitele de conexiuni simultane ale furnizorului dumneavoastră.",
        "privacy-li4": "<strong>Fără urmărire publicitară</strong>: Nu utilizăm trackere publicitare terțe pentru a vă analiza comportamentul în cadrul aplicației.",
        "privacy-li5": "<strong>Transferuri securizate</strong>: Toate datele sincronizate în cloud sunt criptate și transferate în siguranță prin HTTPS.",
        "privacy-h3": "3. Utilizarea informațiilor",
        "privacy-p4": "Informațiile stocate local pe dispozitiv sau sincronizate în contul securizat de cloud sunt utilizate exclusiv pentru:",
        "privacy-li6": "Conectarea la serverele dvs. personale de IPTV.",
        "privacy-li7": "Afișarea listei de canale și a ghidului electronic de programe (EPG).",
        "privacy-li8": "Sincronizarea favoritelor și reluarea redării video de pe un dispozitiv pe altul.",
        "privacy-h4": "4. Servicii terțe",
        "privacy-p5": "Când adăugați o adresă URL a unei liste de redare sau acreditări, dispozitivul dvs. se conectează direct la serverele terțe ale furnizorului dvs. de IPTV. Aceste servere externe sunt guvernate de propriile politici de confidențialitate. Nu suntem responsabili pentru modul în care datele dvs. sunt gestionate de aceste terțe părți.",
        "privacy-h5": "5. Securitate",
        "privacy-p6": "Utilizăm metode standard de criptare oferite de sistemul de operare Android pentru a vă proteja datele de conectare stocate pe dispozitiv.",
        "privacy-h6": "6. Confidențialitatea copiilor",
        "privacy-p7": "Aplicația noastră nu colectează cu bună știință date personale de la copii.",
        "privacy-h7": "7. Contact",
        "privacy-p8": "Dacă au întrebări referitoare la această Politică de confidențialitate, ne pot contacta prin e-mail la:",

        "disc-title": "Declinarea răspunderii legale și non-responsabilitate",
        "disc-date": "Data intrării în vigoare: 26 mai 2026",
        "disc-p1": "Acest software este de fapt un instrument de redare media și nu oferă, distribuie sau conține niciun conținut media de niciun fel. Utilizatorii trebuie să își asigure propriile surse (liste de redare M3U, acreditări de server Xtream Codes etc.).",
        "disc-h1": "1. Absența conținutului multimedia",
        "disc-p2": "IPTV Mediacenter nu oferă fluxuri video, canale TV sau biblioteci de filme și seriale. Aplicația este un instrument neutru care decodifică și afișează listele de redare introduse voluntar de utilizator.",
        "disc-h2": "2. Absența afilierii legale",
        "disc-p3": "IPTV Mediacenter nu are nicio afiliere, parteneriat sau legătură comercială cu furnizorii de fluxuri, revânzătorii de abonamente sau distribuitorii de conținut IPTV. Nu vindem abonamente sau acces la media.",
        "disc-h3": "3. Drepturile de autor și pirateria",
        "disc-p4": "Nu susținem și nu tolerăm difuzarea sau redarea materialelor protejate prin drepturi de autor fără permisiunea explicită a deținătorului drepturilor. Este responsabilitatea strictă a utilizatorului să se asigure că sursele sale de streaming IPTV sunt conforme cu reglementările locale și internaționale în vigoare. IPTV Mediacenter nu poate fi tras la răspundere pentru utilizarea neautorizată a software-ului pentru a reda conținut piratat.",
        "disc-h4": "4. Utilizare conformă",
        "disc-p5": "Utilizarea aplicației noastre trebuie să respecte cu strictețe legile țării dumneavoastră de reședință. Orice utilizare ilicită a software-ului este responsabilitatea exclusivă a utilizatorului final.",
        "disc-h5": "5. Mărci comerciale terțe",
        "disc-p6": "Toate logo-urile, numele de produse sau mărcile comerciale menționate în documentație sau în prezentare aparțin proprietarilor lor respectivi și nu constituie în niciun fel o susținere sau un parteneriat din partea lor.",

        "faq-title": "Întrebări frecvente (FAQ)",
        "faq-q1": "Ce este IPTV Mediacenter?",
        "faq-a1": "IPTV Mediacenter este un player media gratuit și neutru. Vă permite să vizionați propriile liste de redare (M3U, Xtream Codes) cu o interfață de utilizator optimizată pentru TV și mobil.",
        "faq-q2": "Aplicația oferă canale sau abonamente?",
        "faq-a2": "Nu. IPTV Mediacenter nu furnizează niciun flux video, canal TV sau abonament. Trebuie să configurați și să importați propriile surse legale de streaming.",
        "faq-q3": "Pe ce dispozitive pot instala aplicația?",
        "faq-a3": "Aplicația este optimizată pentru Android TV (cu navigare completă prin telecomandă), smartphone-uri/tablete Android și Windows (descărcabilă din Microsoft Store)."
    }
};

function changeLanguage(lang) {
    localStorage.setItem("selected_lang", lang);
    applyTranslations(lang);
}

function applyTranslations(lang) {
    const dict = translations[lang] || translations["fr"];
    
    // Set html lang and dir attributes
    document.documentElement.lang = lang;
    if (lang === "ar") {
        document.documentElement.dir = "rtl";
        document.body.classList.add("rtl-layout");
    } else {
        document.documentElement.dir = "ltr";
        document.body.classList.remove("rtl-layout");
    }

    // Translate all elements with data-i18n
    document.querySelectorAll("[data-i18n]").forEach(element => {
        const key = element.getAttribute("data-i18n");
        if (dict[key]) {
            if (element.tagName === "INPUT" || element.tagName === "TEXTAREA") {
                element.placeholder = dict[key];
            } else {
                element.innerHTML = dict[key];
            }
        }
    });
    
    // Update language select dropdown value
    const langSelect = document.getElementById("lang-select");
    if (langSelect) {
        langSelect.value = lang;
    }
}

// Automatically detect language on load
document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("selected_lang");
    const browserLang = navigator.language.substring(0, 2);
    const defaultLang = savedLang || (translations[browserLang] ? browserLang : "fr");
    applyTranslations(defaultLang);
});
